// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: plugin/squilla_plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_squilla_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_squilla_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_squilla_plugin_proto_rawDescGZIP(), []int{0}
}

type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostServiceId uint32                 `protobuf:"varint,1,opt,name=host_service_id,json=hostServiceId,proto3" json:"host_service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_plugin_squilla_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_squilla_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_squilla_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InitializeRequest) GetHostServiceId() uint32 {
	if x != nil {
		return x.HostServiceId
	}
	return 0
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_plugin_squilla_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_squilla_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_plugin_squilla_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Subscription) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SubscriptionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionList) Reset() {
	*x = SubscriptionList{}
	mi := &file_plugin_squilla_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionList) ProtoMessage() {}

func (x *SubscriptionList) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_squilla_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionList.ProtoReflect.Descriptor instead.
func (*SubscriptionList) Descriptor() ([]byte, []int) {
	return file_plugin_squilla_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriptionList) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded event payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_plugin_squilla_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_squilla_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_plugin_squilla_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *EventRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handled       bool                   `protobuf:"varint,1,opt,name=handled,proto3" json:"handled,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // JSON-encoded result data (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_plugin_squilla_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_squilla_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_plugin_squilla_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *EventResponse) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

func (x *EventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EventResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type PluginHTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // path relative to /admin/api/ext/{slug}/
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	QueryParams   map[string]string      `protobuf:"bytes,5,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PathParams    map[string]string      `protobuf:"bytes,6,rep,name=path_params,json=pathParams,proto3" json:"path_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., :id from routes
	UserId        uint64                 `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                                                      // authenticated user ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginHTTPRequest) Reset() {
	*x = PluginHTTPRequest{}
	mi := &file_plugin_squilla_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginHTTPRequest) ProtoMessage() {}

func (x *PluginHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_squilla_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginHTTPRequest.ProtoReflect.Descriptor instead.
func (*PluginHTTPRequest) Descriptor() ([]byte, []int) {
	return file_plugin_squilla_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *PluginHTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PluginHTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PluginHTTPRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PluginHTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PluginHTTPRequest) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *PluginHTTPRequest) GetPathParams() map[string]string {
	if x != nil {
		return x.PathParams
	}
	return nil
}

func (x *PluginHTTPRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PluginHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginHTTPResponse) Reset() {
	*x = PluginHTTPResponse{}
	mi := &file_plugin_squilla_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginHTTPResponse) ProtoMessage() {}

func (x *PluginHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_squilla_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginHTTPResponse.ProtoReflect.Descriptor instead.
func (*PluginHTTPResponse) Descriptor() ([]byte, []int) {
	return file_plugin_squilla_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *PluginHTTPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PluginHTTPResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PluginHTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_plugin_squilla_plugin_proto protoreflect.FileDescriptor

const file_plugin_squilla_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1bplugin/squilla_plugin.proto\x12\rsquillaplugin\"\a\n" +
	"\x05Empty\";\n" +
	"\x11InitializeRequest\x12&\n" +
	"\x0fhost_service_id\x18\x01 \x01(\rR\rhostServiceId\"I\n" +
	"\fSubscription\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\"U\n" +
	"\x10SubscriptionList\x12A\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1b.squillaplugin.SubscriptionR\rsubscriptions\"@\n" +
	"\fEventRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"W\n" +
	"\rEventResponse\x12\x18\n" +
	"\ahandled\x18\x01 \x01(\bR\ahandled\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\"\x99\x04\n" +
	"\x11PluginHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12G\n" +
	"\aheaders\x18\x03 \x03(\v2-.squillaplugin.PluginHTTPRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12T\n" +
	"\fquery_params\x18\x05 \x03(\v21.squillaplugin.PluginHTTPRequest.QueryParamsEntryR\vqueryParams\x12Q\n" +
	"\vpath_params\x18\x06 \x03(\v20.squillaplugin.PluginHTTPRequest.PathParamsEntryR\n" +
	"pathParams\x12\x17\n" +
	"\auser_id\x18\a \x01(\x04R\x06userId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10QueryParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fPathParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x12PluginHTTPResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12H\n" +
	"\aheaders\x18\x02 \x03(\v2..squillaplugin.PluginHTTPResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xfe\x02\n" +
	"\x0fExtensionPlugin\x12I\n" +
	"\x10GetSubscriptions\x12\x14.squillaplugin.Empty\x1a\x1f.squillaplugin.SubscriptionList\x12H\n" +
	"\vHandleEvent\x12\x1b.squillaplugin.EventRequest\x1a\x1c.squillaplugin.EventResponse\x126\n" +
	"\bShutdown\x12\x14.squillaplugin.Empty\x1a\x14.squillaplugin.Empty\x12D\n" +
	"\n" +
	"Initialize\x12 .squillaplugin.InitializeRequest\x1a\x14.squillaplugin.Empty\x12X\n" +
	"\x11HandleHTTPRequest\x12 .squillaplugin.PluginHTTPRequest\x1a!.squillaplugin.PluginHTTPResponseB\x1aZ\x18squilla/pkg/plugin/protob\x06proto3"

var (
	file_plugin_squilla_plugin_proto_rawDescOnce sync.Once
	file_plugin_squilla_plugin_proto_rawDescData []byte
)

func file_plugin_squilla_plugin_proto_rawDescGZIP() []byte {
	file_plugin_squilla_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_squilla_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_squilla_plugin_proto_rawDesc), len(file_plugin_squilla_plugin_proto_rawDesc)))
	})
	return file_plugin_squilla_plugin_proto_rawDescData
}

var file_plugin_squilla_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_plugin_squilla_plugin_proto_goTypes = []any{
	(*Empty)(nil),              // 0: squillaplugin.Empty
	(*InitializeRequest)(nil),  // 1: squillaplugin.InitializeRequest
	(*Subscription)(nil),       // 2: squillaplugin.Subscription
	(*SubscriptionList)(nil),   // 3: squillaplugin.SubscriptionList
	(*EventRequest)(nil),       // 4: squillaplugin.EventRequest
	(*EventResponse)(nil),      // 5: squillaplugin.EventResponse
	(*PluginHTTPRequest)(nil),  // 6: squillaplugin.PluginHTTPRequest
	(*PluginHTTPResponse)(nil), // 7: squillaplugin.PluginHTTPResponse
	nil,                        // 8: squillaplugin.PluginHTTPRequest.HeadersEntry
	nil,                        // 9: squillaplugin.PluginHTTPRequest.QueryParamsEntry
	nil,                        // 10: squillaplugin.PluginHTTPRequest.PathParamsEntry
	nil,                        // 11: squillaplugin.PluginHTTPResponse.HeadersEntry
}
var file_plugin_squilla_plugin_proto_depIdxs = []int32{
	2,  // 0: squillaplugin.SubscriptionList.subscriptions:type_name -> squillaplugin.Subscription
	8,  // 1: squillaplugin.PluginHTTPRequest.headers:type_name -> squillaplugin.PluginHTTPRequest.HeadersEntry
	9,  // 2: squillaplugin.PluginHTTPRequest.query_params:type_name -> squillaplugin.PluginHTTPRequest.QueryParamsEntry
	10, // 3: squillaplugin.PluginHTTPRequest.path_params:type_name -> squillaplugin.PluginHTTPRequest.PathParamsEntry
	11, // 4: squillaplugin.PluginHTTPResponse.headers:type_name -> squillaplugin.PluginHTTPResponse.HeadersEntry
	0,  // 5: squillaplugin.ExtensionPlugin.GetSubscriptions:input_type -> squillaplugin.Empty
	4,  // 6: squillaplugin.ExtensionPlugin.HandleEvent:input_type -> squillaplugin.EventRequest
	0,  // 7: squillaplugin.ExtensionPlugin.Shutdown:input_type -> squillaplugin.Empty
	1,  // 8: squillaplugin.ExtensionPlugin.Initialize:input_type -> squillaplugin.InitializeRequest
	6,  // 9: squillaplugin.ExtensionPlugin.HandleHTTPRequest:input_type -> squillaplugin.PluginHTTPRequest
	3,  // 10: squillaplugin.ExtensionPlugin.GetSubscriptions:output_type -> squillaplugin.SubscriptionList
	5,  // 11: squillaplugin.ExtensionPlugin.HandleEvent:output_type -> squillaplugin.EventResponse
	0,  // 12: squillaplugin.ExtensionPlugin.Shutdown:output_type -> squillaplugin.Empty
	0,  // 13: squillaplugin.ExtensionPlugin.Initialize:output_type -> squillaplugin.Empty
	7,  // 14: squillaplugin.ExtensionPlugin.HandleHTTPRequest:output_type -> squillaplugin.PluginHTTPResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_plugin_squilla_plugin_proto_init() }
func file_plugin_squilla_plugin_proto_init() {
	if File_plugin_squilla_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_squilla_plugin_proto_rawDesc), len(file_plugin_squilla_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_squilla_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_squilla_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_squilla_plugin_proto_msgTypes,
	}.Build()
	File_plugin_squilla_plugin_proto = out.File
	file_plugin_squilla_plugin_proto_goTypes = nil
	file_plugin_squilla_plugin_proto_depIdxs = nil
}
