-- Seed the languages table with the canonical set of world languages so the
-- "Add Language" picker on a fresh install isn't an empty page. Only English
-- is activated by default — every new entry is is_active=false. Existing rows
-- are never touched (ON CONFLICT (code) DO NOTHING), so user toggles persist.
INSERT INTO languages (code, slug, name, native_name, flag, is_default, is_active, sort_order) VALUES
    ('en',    'en',    'English',          'English',           '🇬🇧', TRUE,  TRUE,  0),
    ('es',    'es',    'Spanish',          'Español',           '🇪🇸', FALSE, FALSE, 10),
    ('fr',    'fr',    'French',           'Français',          '🇫🇷', FALSE, FALSE, 20),
    ('de',    'de',    'German',           'Deutsch',           '🇩🇪', FALSE, FALSE, 30),
    ('it',    'it',    'Italian',          'Italiano',          '🇮🇹', FALSE, FALSE, 40),
    ('pt',    'pt',    'Portuguese',       'Português',         '🇵🇹', FALSE, FALSE, 50),
    ('pt-br', 'pt-br', 'Portuguese (BR)',  'Português (Brasil)','🇧🇷', FALSE, FALSE, 51),
    ('nl',    'nl',    'Dutch',            'Nederlands',        '🇳🇱', FALSE, FALSE, 60),
    ('sv',    'sv',    'Swedish',          'Svenska',           '🇸🇪', FALSE, FALSE, 70),
    ('no',    'no',    'Norwegian',        'Norsk',             '🇳🇴', FALSE, FALSE, 80),
    ('da',    'da',    'Danish',           'Dansk',             '🇩🇰', FALSE, FALSE, 90),
    ('fi',    'fi',    'Finnish',          'Suomi',             '🇫🇮', FALSE, FALSE, 100),
    ('is',    'is',    'Icelandic',        'Íslenska',          '🇮🇸', FALSE, FALSE, 110),
    ('pl',    'pl',    'Polish',           'Polski',            '🇵🇱', FALSE, FALSE, 120),
    ('cs',    'cs',    'Czech',            'Čeština',           '🇨🇿', FALSE, FALSE, 130),
    ('sk',    'sk',    'Slovak',           'Slovenčina',        '🇸🇰', FALSE, FALSE, 140),
    ('hu',    'hu',    'Hungarian',        'Magyar',            '🇭🇺', FALSE, FALSE, 150),
    ('ro',    'ro',    'Romanian',         'Română',            '🇷🇴', FALSE, FALSE, 160),
    ('bg',    'bg',    'Bulgarian',        'Български',         '🇧🇬', FALSE, FALSE, 170),
    ('hr',    'hr',    'Croatian',         'Hrvatski',          '🇭🇷', FALSE, FALSE, 180),
    ('sr',    'sr',    'Serbian',          'Српски',            '🇷🇸', FALSE, FALSE, 190),
    ('sl',    'sl',    'Slovenian',        'Slovenščina',       '🇸🇮', FALSE, FALSE, 200),
    ('uk',    'uk',    'Ukrainian',        'Українська',        '🇺🇦', FALSE, FALSE, 210),
    ('ru',    'ru',    'Russian',          'Русский',           '🇷🇺', FALSE, FALSE, 220),
    ('be',    'be',    'Belarusian',       'Беларуская',        '🇧🇾', FALSE, FALSE, 230),
    ('lt',    'lt',    'Lithuanian',       'Lietuvių',          '🇱🇹', FALSE, FALSE, 240),
    ('lv',    'lv',    'Latvian',          'Latviešu',          '🇱🇻', FALSE, FALSE, 250),
    ('et',    'et',    'Estonian',         'Eesti',             '🇪🇪', FALSE, FALSE, 260),
    ('el',    'el',    'Greek',            'Ελληνικά',          '🇬🇷', FALSE, FALSE, 270),
    ('tr',    'tr',    'Turkish',          'Türkçe',            '🇹🇷', FALSE, FALSE, 280),
    ('ar',    'ar',    'Arabic',           'العربية',           '🇸🇦', FALSE, FALSE, 290),
    ('he',    'he',    'Hebrew',           'עברית',             '🇮🇱', FALSE, FALSE, 300),
    ('fa',    'fa',    'Persian',          'فارسی',             '🇮🇷', FALSE, FALSE, 310),
    ('hi',    'hi',    'Hindi',            'हिन्दी',              '🇮🇳', FALSE, FALSE, 320),
    ('bn',    'bn',    'Bengali',          'বাংলা',              '🇧🇩', FALSE, FALSE, 330),
    ('ur',    'ur',    'Urdu',             'اردو',              '🇵🇰', FALSE, FALSE, 340),
    ('th',    'th',    'Thai',             'ไทย',               '🇹🇭', FALSE, FALSE, 350),
    ('vi',    'vi',    'Vietnamese',       'Tiếng Việt',        '🇻🇳', FALSE, FALSE, 360),
    ('id',    'id',    'Indonesian',       'Bahasa Indonesia',  '🇮🇩', FALSE, FALSE, 370),
    ('ms',    'ms',    'Malay',            'Bahasa Melayu',     '🇲🇾', FALSE, FALSE, 380),
    ('tl',    'tl',    'Filipino',         'Filipino',          '🇵🇭', FALSE, FALSE, 390),
    ('ja',    'ja',    'Japanese',         '日本語',             '🇯🇵', FALSE, FALSE, 400),
    ('ko',    'ko',    'Korean',           '한국어',             '🇰🇷', FALSE, FALSE, 410),
    ('zh',    'zh',    'Chinese (Simp.)',  '简体中文',           '🇨🇳', FALSE, FALSE, 420),
    ('zh-tw', 'zh-tw', 'Chinese (Trad.)',  '繁體中文',           '🇹🇼', FALSE, FALSE, 421),
    ('sw',    'sw',    'Swahili',          'Kiswahili',         '🇰🇪', FALSE, FALSE, 430),
    ('af',    'af',    'Afrikaans',        'Afrikaans',         '🇿🇦', FALSE, FALSE, 440),
    ('am',    'am',    'Amharic',          'አማርኛ',              '🇪🇹', FALSE, FALSE, 450),
    ('ca',    'ca',    'Catalan',          'Català',            '🇪🇸', FALSE, FALSE, 460),
    ('eu',    'eu',    'Basque',           'Euskara',           '🇪🇸', FALSE, FALSE, 470),
    ('gl',    'gl',    'Galician',         'Galego',            '🇪🇸', FALSE, FALSE, 480),
    ('ga',    'ga',    'Irish',            'Gaeilge',           '🇮🇪', FALSE, FALSE, 490),
    ('cy',    'cy',    'Welsh',            'Cymraeg',           '🇬🇧', FALSE, FALSE, 500),
    ('mt',    'mt',    'Maltese',          'Malti',             '🇲🇹', FALSE, FALSE, 510),
    ('sq',    'sq',    'Albanian',         'Shqip',             '🇦🇱', FALSE, FALSE, 520),
    ('mk',    'mk',    'Macedonian',       'Македонски',        '🇲🇰', FALSE, FALSE, 530),
    ('bs',    'bs',    'Bosnian',          'Bosanski',          '🇧🇦', FALSE, FALSE, 540),
    ('ka',    'ka',    'Georgian',         'ქართული',           '🇬🇪', FALSE, FALSE, 550),
    ('hy',    'hy',    'Armenian',         'Հայերեն',           '🇦🇲', FALSE, FALSE, 560),
    ('az',    'az',    'Azerbaijani',      'Azərbaycanca',      '🇦🇿', FALSE, FALSE, 570),
    ('kk',    'kk',    'Kazakh',           'Қазақша',           '🇰🇿', FALSE, FALSE, 580),
    ('uz',    'uz',    'Uzbek',            'Oʻzbekcha',         '🇺🇿', FALSE, FALSE, 590)
ON CONFLICT (code) DO NOTHING;
