// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: coreapi/squilla_coreapi.proto

package coreapipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SquillaHost_GetNode_FullMethodName           = "/squilla.coreapi.SquillaHost/GetNode"
	SquillaHost_QueryNodes_FullMethodName        = "/squilla.coreapi.SquillaHost/QueryNodes"
	SquillaHost_ListTaxonomyTerms_FullMethodName = "/squilla.coreapi.SquillaHost/ListTaxonomyTerms"
	SquillaHost_CreateNode_FullMethodName        = "/squilla.coreapi.SquillaHost/CreateNode"
	SquillaHost_UpdateNode_FullMethodName        = "/squilla.coreapi.SquillaHost/UpdateNode"
	SquillaHost_DeleteNode_FullMethodName        = "/squilla.coreapi.SquillaHost/DeleteNode"
	SquillaHost_ListTerms_FullMethodName         = "/squilla.coreapi.SquillaHost/ListTerms"
	SquillaHost_GetTerm_FullMethodName           = "/squilla.coreapi.SquillaHost/GetTerm"
	SquillaHost_CreateTerm_FullMethodName        = "/squilla.coreapi.SquillaHost/CreateTerm"
	SquillaHost_UpdateTerm_FullMethodName        = "/squilla.coreapi.SquillaHost/UpdateTerm"
	SquillaHost_DeleteTerm_FullMethodName        = "/squilla.coreapi.SquillaHost/DeleteTerm"
	SquillaHost_RegisterTaxonomy_FullMethodName  = "/squilla.coreapi.SquillaHost/RegisterTaxonomy"
	SquillaHost_GetTaxonomy_FullMethodName       = "/squilla.coreapi.SquillaHost/GetTaxonomy"
	SquillaHost_ListTaxonomies_FullMethodName    = "/squilla.coreapi.SquillaHost/ListTaxonomies"
	SquillaHost_UpdateTaxonomy_FullMethodName    = "/squilla.coreapi.SquillaHost/UpdateTaxonomy"
	SquillaHost_DeleteTaxonomy_FullMethodName    = "/squilla.coreapi.SquillaHost/DeleteTaxonomy"
	SquillaHost_GetSetting_FullMethodName        = "/squilla.coreapi.SquillaHost/GetSetting"
	SquillaHost_SetSetting_FullMethodName        = "/squilla.coreapi.SquillaHost/SetSetting"
	SquillaHost_GetSettings_FullMethodName       = "/squilla.coreapi.SquillaHost/GetSettings"
	SquillaHost_EmitEvent_FullMethodName         = "/squilla.coreapi.SquillaHost/EmitEvent"
	SquillaHost_SendEmail_FullMethodName         = "/squilla.coreapi.SquillaHost/SendEmail"
	SquillaHost_GetMenu_FullMethodName           = "/squilla.coreapi.SquillaHost/GetMenu"
	SquillaHost_GetMenus_FullMethodName          = "/squilla.coreapi.SquillaHost/GetMenus"
	SquillaHost_GetUser_FullMethodName           = "/squilla.coreapi.SquillaHost/GetUser"
	SquillaHost_QueryUsers_FullMethodName        = "/squilla.coreapi.SquillaHost/QueryUsers"
	SquillaHost_Fetch_FullMethodName             = "/squilla.coreapi.SquillaHost/Fetch"
	SquillaHost_Log_FullMethodName               = "/squilla.coreapi.SquillaHost/Log"
	SquillaHost_DataGet_FullMethodName           = "/squilla.coreapi.SquillaHost/DataGet"
	SquillaHost_DataQuery_FullMethodName         = "/squilla.coreapi.SquillaHost/DataQuery"
	SquillaHost_DataCreate_FullMethodName        = "/squilla.coreapi.SquillaHost/DataCreate"
	SquillaHost_DataUpdate_FullMethodName        = "/squilla.coreapi.SquillaHost/DataUpdate"
	SquillaHost_DataDelete_FullMethodName        = "/squilla.coreapi.SquillaHost/DataDelete"
	SquillaHost_DataExec_FullMethodName          = "/squilla.coreapi.SquillaHost/DataExec"
	SquillaHost_StoreFile_FullMethodName         = "/squilla.coreapi.SquillaHost/StoreFile"
	SquillaHost_DeleteFile_FullMethodName        = "/squilla.coreapi.SquillaHost/DeleteFile"
	SquillaHost_RegisterNodeType_FullMethodName  = "/squilla.coreapi.SquillaHost/RegisterNodeType"
	SquillaHost_GetNodeType_FullMethodName       = "/squilla.coreapi.SquillaHost/GetNodeType"
	SquillaHost_ListNodeTypes_FullMethodName     = "/squilla.coreapi.SquillaHost/ListNodeTypes"
	SquillaHost_UpdateNodeType_FullMethodName    = "/squilla.coreapi.SquillaHost/UpdateNodeType"
	SquillaHost_DeleteNodeType_FullMethodName    = "/squilla.coreapi.SquillaHost/DeleteNodeType"
)

// SquillaHostClient is the client API for SquillaHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SquillaHostClient interface {
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	QueryNodes(ctx context.Context, in *QueryNodesRequest, opts ...grpc.CallOption) (*QueryNodesResponse, error)
	ListTaxonomyTerms(ctx context.Context, in *ListTaxonomyTermsRequest, opts ...grpc.CallOption) (*ListTaxonomyTermsResponse, error)
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*Empty, error)
	// Taxonomies
	ListTerms(ctx context.Context, in *ListTermsRequest, opts ...grpc.CallOption) (*ListTermsResponse, error)
	GetTerm(ctx context.Context, in *GetTermRequest, opts ...grpc.CallOption) (*TermResponse, error)
	CreateTerm(ctx context.Context, in *CreateTermRequest, opts ...grpc.CallOption) (*TermResponse, error)
	UpdateTerm(ctx context.Context, in *UpdateTermRequest, opts ...grpc.CallOption) (*TermResponse, error)
	DeleteTerm(ctx context.Context, in *DeleteTermRequest, opts ...grpc.CallOption) (*Empty, error)
	// Taxonomy Definitions
	RegisterTaxonomy(ctx context.Context, in *TaxonomyInputMessage, opts ...grpc.CallOption) (*TaxonomyResponse, error)
	GetTaxonomy(ctx context.Context, in *GetTaxonomyRequest, opts ...grpc.CallOption) (*TaxonomyResponse, error)
	ListTaxonomies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaxonomyListResponse, error)
	UpdateTaxonomy(ctx context.Context, in *UpdateTaxonomyRequest, opts ...grpc.CallOption) (*TaxonomyResponse, error)
	DeleteTaxonomy(ctx context.Context, in *DeleteTaxonomyRequest, opts ...grpc.CallOption) (*Empty, error)
	GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*SettingResponse, error)
	SetSetting(ctx context.Context, in *SetSettingRequest, opts ...grpc.CallOption) (*Empty, error)
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error)
	EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*Empty, error)
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*Empty, error)
	GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*MenuResponse, error)
	GetMenus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	QueryUsers(ctx context.Context, in *QueryUsersRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error)
	DataGet(ctx context.Context, in *DataGetRequest, opts ...grpc.CallOption) (*DataRowResponse, error)
	DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
	DataCreate(ctx context.Context, in *DataCreateRequest, opts ...grpc.CallOption) (*DataRowResponse, error)
	DataUpdate(ctx context.Context, in *DataUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	DataDelete(ctx context.Context, in *DataDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	DataExec(ctx context.Context, in *DataExecRequest, opts ...grpc.CallOption) (*DataExecResponse, error)
	StoreFile(ctx context.Context, in *StoreFileRequest, opts ...grpc.CallOption) (*StoreFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*Empty, error)
	RegisterNodeType(ctx context.Context, in *NodeTypeInputMessage, opts ...grpc.CallOption) (*NodeTypeResponse, error)
	GetNodeType(ctx context.Context, in *GetNodeTypeRequest, opts ...grpc.CallOption) (*NodeTypeResponse, error)
	ListNodeTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeTypeListResponse, error)
	UpdateNodeType(ctx context.Context, in *UpdateNodeTypeRequest, opts ...grpc.CallOption) (*NodeTypeResponse, error)
	DeleteNodeType(ctx context.Context, in *DeleteNodeTypeRequest, opts ...grpc.CallOption) (*Empty, error)
}

type squillaHostClient struct {
	cc grpc.ClientConnInterface
}

func NewSquillaHostClient(cc grpc.ClientConnInterface) SquillaHostClient {
	return &squillaHostClient{cc}
}

func (c *squillaHostClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, SquillaHost_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) QueryNodes(ctx context.Context, in *QueryNodesRequest, opts ...grpc.CallOption) (*QueryNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryNodesResponse)
	err := c.cc.Invoke(ctx, SquillaHost_QueryNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) ListTaxonomyTerms(ctx context.Context, in *ListTaxonomyTermsRequest, opts ...grpc.CallOption) (*ListTaxonomyTermsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaxonomyTermsResponse)
	err := c.cc.Invoke(ctx, SquillaHost_ListTaxonomyTerms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, SquillaHost_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, SquillaHost_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) ListTerms(ctx context.Context, in *ListTermsRequest, opts ...grpc.CallOption) (*ListTermsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTermsResponse)
	err := c.cc.Invoke(ctx, SquillaHost_ListTerms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) GetTerm(ctx context.Context, in *GetTermRequest, opts ...grpc.CallOption) (*TermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TermResponse)
	err := c.cc.Invoke(ctx, SquillaHost_GetTerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) CreateTerm(ctx context.Context, in *CreateTermRequest, opts ...grpc.CallOption) (*TermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TermResponse)
	err := c.cc.Invoke(ctx, SquillaHost_CreateTerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) UpdateTerm(ctx context.Context, in *UpdateTermRequest, opts ...grpc.CallOption) (*TermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TermResponse)
	err := c.cc.Invoke(ctx, SquillaHost_UpdateTerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DeleteTerm(ctx context.Context, in *DeleteTermRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_DeleteTerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) RegisterTaxonomy(ctx context.Context, in *TaxonomyInputMessage, opts ...grpc.CallOption) (*TaxonomyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaxonomyResponse)
	err := c.cc.Invoke(ctx, SquillaHost_RegisterTaxonomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) GetTaxonomy(ctx context.Context, in *GetTaxonomyRequest, opts ...grpc.CallOption) (*TaxonomyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaxonomyResponse)
	err := c.cc.Invoke(ctx, SquillaHost_GetTaxonomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) ListTaxonomies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaxonomyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaxonomyListResponse)
	err := c.cc.Invoke(ctx, SquillaHost_ListTaxonomies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) UpdateTaxonomy(ctx context.Context, in *UpdateTaxonomyRequest, opts ...grpc.CallOption) (*TaxonomyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaxonomyResponse)
	err := c.cc.Invoke(ctx, SquillaHost_UpdateTaxonomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DeleteTaxonomy(ctx context.Context, in *DeleteTaxonomyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_DeleteTaxonomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*SettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingResponse)
	err := c.cc.Invoke(ctx, SquillaHost_GetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) SetSetting(ctx context.Context, in *SetSettingRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_SetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, SquillaHost_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_EmitEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*MenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuResponse)
	err := c.cc.Invoke(ctx, SquillaHost_GetMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) GetMenus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuListResponse)
	err := c.cc.Invoke(ctx, SquillaHost_GetMenus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, SquillaHost_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) QueryUsers(ctx context.Context, in *QueryUsersRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, SquillaHost_QueryUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, SquillaHost_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DataGet(ctx context.Context, in *DataGetRequest, opts ...grpc.CallOption) (*DataRowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataRowResponse)
	err := c.cc.Invoke(ctx, SquillaHost_DataGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, SquillaHost_DataQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DataCreate(ctx context.Context, in *DataCreateRequest, opts ...grpc.CallOption) (*DataRowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataRowResponse)
	err := c.cc.Invoke(ctx, SquillaHost_DataCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DataUpdate(ctx context.Context, in *DataUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_DataUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DataDelete(ctx context.Context, in *DataDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_DataDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DataExec(ctx context.Context, in *DataExecRequest, opts ...grpc.CallOption) (*DataExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataExecResponse)
	err := c.cc.Invoke(ctx, SquillaHost_DataExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) StoreFile(ctx context.Context, in *StoreFileRequest, opts ...grpc.CallOption) (*StoreFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreFileResponse)
	err := c.cc.Invoke(ctx, SquillaHost_StoreFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) RegisterNodeType(ctx context.Context, in *NodeTypeInputMessage, opts ...grpc.CallOption) (*NodeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeTypeResponse)
	err := c.cc.Invoke(ctx, SquillaHost_RegisterNodeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) GetNodeType(ctx context.Context, in *GetNodeTypeRequest, opts ...grpc.CallOption) (*NodeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeTypeResponse)
	err := c.cc.Invoke(ctx, SquillaHost_GetNodeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) ListNodeTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeTypeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeTypeListResponse)
	err := c.cc.Invoke(ctx, SquillaHost_ListNodeTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) UpdateNodeType(ctx context.Context, in *UpdateNodeTypeRequest, opts ...grpc.CallOption) (*NodeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeTypeResponse)
	err := c.cc.Invoke(ctx, SquillaHost_UpdateNodeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *squillaHostClient) DeleteNodeType(ctx context.Context, in *DeleteNodeTypeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SquillaHost_DeleteNodeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SquillaHostServer is the server API for SquillaHost service.
// All implementations must embed UnimplementedSquillaHostServer
// for forward compatibility.
type SquillaHostServer interface {
	GetNode(context.Context, *GetNodeRequest) (*NodeResponse, error)
	QueryNodes(context.Context, *QueryNodesRequest) (*QueryNodesResponse, error)
	ListTaxonomyTerms(context.Context, *ListTaxonomyTermsRequest) (*ListTaxonomyTermsResponse, error)
	CreateNode(context.Context, *CreateNodeRequest) (*NodeResponse, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*NodeResponse, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*Empty, error)
	// Taxonomies
	ListTerms(context.Context, *ListTermsRequest) (*ListTermsResponse, error)
	GetTerm(context.Context, *GetTermRequest) (*TermResponse, error)
	CreateTerm(context.Context, *CreateTermRequest) (*TermResponse, error)
	UpdateTerm(context.Context, *UpdateTermRequest) (*TermResponse, error)
	DeleteTerm(context.Context, *DeleteTermRequest) (*Empty, error)
	// Taxonomy Definitions
	RegisterTaxonomy(context.Context, *TaxonomyInputMessage) (*TaxonomyResponse, error)
	GetTaxonomy(context.Context, *GetTaxonomyRequest) (*TaxonomyResponse, error)
	ListTaxonomies(context.Context, *Empty) (*TaxonomyListResponse, error)
	UpdateTaxonomy(context.Context, *UpdateTaxonomyRequest) (*TaxonomyResponse, error)
	DeleteTaxonomy(context.Context, *DeleteTaxonomyRequest) (*Empty, error)
	GetSetting(context.Context, *GetSettingRequest) (*SettingResponse, error)
	SetSetting(context.Context, *SetSettingRequest) (*Empty, error)
	GetSettings(context.Context, *GetSettingsRequest) (*SettingsResponse, error)
	EmitEvent(context.Context, *EmitEventRequest) (*Empty, error)
	SendEmail(context.Context, *SendEmailRequest) (*Empty, error)
	GetMenu(context.Context, *GetMenuRequest) (*MenuResponse, error)
	GetMenus(context.Context, *Empty) (*MenuListResponse, error)
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	QueryUsers(context.Context, *QueryUsersRequest) (*UserListResponse, error)
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	Log(context.Context, *LogRequest) (*Empty, error)
	DataGet(context.Context, *DataGetRequest) (*DataRowResponse, error)
	DataQuery(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
	DataCreate(context.Context, *DataCreateRequest) (*DataRowResponse, error)
	DataUpdate(context.Context, *DataUpdateRequest) (*Empty, error)
	DataDelete(context.Context, *DataDeleteRequest) (*Empty, error)
	DataExec(context.Context, *DataExecRequest) (*DataExecResponse, error)
	StoreFile(context.Context, *StoreFileRequest) (*StoreFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*Empty, error)
	RegisterNodeType(context.Context, *NodeTypeInputMessage) (*NodeTypeResponse, error)
	GetNodeType(context.Context, *GetNodeTypeRequest) (*NodeTypeResponse, error)
	ListNodeTypes(context.Context, *Empty) (*NodeTypeListResponse, error)
	UpdateNodeType(context.Context, *UpdateNodeTypeRequest) (*NodeTypeResponse, error)
	DeleteNodeType(context.Context, *DeleteNodeTypeRequest) (*Empty, error)
	mustEmbedUnimplementedSquillaHostServer()
}

// UnimplementedSquillaHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSquillaHostServer struct{}

func (UnimplementedSquillaHostServer) GetNode(context.Context, *GetNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedSquillaHostServer) QueryNodes(context.Context, *QueryNodesRequest) (*QueryNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryNodes not implemented")
}
func (UnimplementedSquillaHostServer) ListTaxonomyTerms(context.Context, *ListTaxonomyTermsRequest) (*ListTaxonomyTermsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaxonomyTerms not implemented")
}
func (UnimplementedSquillaHostServer) CreateNode(context.Context, *CreateNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedSquillaHostServer) UpdateNode(context.Context, *UpdateNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedSquillaHostServer) DeleteNode(context.Context, *DeleteNodeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedSquillaHostServer) ListTerms(context.Context, *ListTermsRequest) (*ListTermsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTerms not implemented")
}
func (UnimplementedSquillaHostServer) GetTerm(context.Context, *GetTermRequest) (*TermResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTerm not implemented")
}
func (UnimplementedSquillaHostServer) CreateTerm(context.Context, *CreateTermRequest) (*TermResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTerm not implemented")
}
func (UnimplementedSquillaHostServer) UpdateTerm(context.Context, *UpdateTermRequest) (*TermResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTerm not implemented")
}
func (UnimplementedSquillaHostServer) DeleteTerm(context.Context, *DeleteTermRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTerm not implemented")
}
func (UnimplementedSquillaHostServer) RegisterTaxonomy(context.Context, *TaxonomyInputMessage) (*TaxonomyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTaxonomy not implemented")
}
func (UnimplementedSquillaHostServer) GetTaxonomy(context.Context, *GetTaxonomyRequest) (*TaxonomyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaxonomy not implemented")
}
func (UnimplementedSquillaHostServer) ListTaxonomies(context.Context, *Empty) (*TaxonomyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaxonomies not implemented")
}
func (UnimplementedSquillaHostServer) UpdateTaxonomy(context.Context, *UpdateTaxonomyRequest) (*TaxonomyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTaxonomy not implemented")
}
func (UnimplementedSquillaHostServer) DeleteTaxonomy(context.Context, *DeleteTaxonomyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTaxonomy not implemented")
}
func (UnimplementedSquillaHostServer) GetSetting(context.Context, *GetSettingRequest) (*SettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSetting not implemented")
}
func (UnimplementedSquillaHostServer) SetSetting(context.Context, *SetSettingRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSetting not implemented")
}
func (UnimplementedSquillaHostServer) GetSettings(context.Context, *GetSettingsRequest) (*SettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedSquillaHostServer) EmitEvent(context.Context, *EmitEventRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitEvent not implemented")
}
func (UnimplementedSquillaHostServer) SendEmail(context.Context, *SendEmailRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedSquillaHostServer) GetMenu(context.Context, *GetMenuRequest) (*MenuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenu not implemented")
}
func (UnimplementedSquillaHostServer) GetMenus(context.Context, *Empty) (*MenuListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenus not implemented")
}
func (UnimplementedSquillaHostServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedSquillaHostServer) QueryUsers(context.Context, *QueryUsersRequest) (*UserListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryUsers not implemented")
}
func (UnimplementedSquillaHostServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedSquillaHostServer) Log(context.Context, *LogRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedSquillaHostServer) DataGet(context.Context, *DataGetRequest) (*DataRowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataGet not implemented")
}
func (UnimplementedSquillaHostServer) DataQuery(context.Context, *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataQuery not implemented")
}
func (UnimplementedSquillaHostServer) DataCreate(context.Context, *DataCreateRequest) (*DataRowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataCreate not implemented")
}
func (UnimplementedSquillaHostServer) DataUpdate(context.Context, *DataUpdateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DataUpdate not implemented")
}
func (UnimplementedSquillaHostServer) DataDelete(context.Context, *DataDeleteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DataDelete not implemented")
}
func (UnimplementedSquillaHostServer) DataExec(context.Context, *DataExecRequest) (*DataExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataExec not implemented")
}
func (UnimplementedSquillaHostServer) StoreFile(context.Context, *StoreFileRequest) (*StoreFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreFile not implemented")
}
func (UnimplementedSquillaHostServer) DeleteFile(context.Context, *DeleteFileRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedSquillaHostServer) RegisterNodeType(context.Context, *NodeTypeInputMessage) (*NodeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNodeType not implemented")
}
func (UnimplementedSquillaHostServer) GetNodeType(context.Context, *GetNodeTypeRequest) (*NodeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeType not implemented")
}
func (UnimplementedSquillaHostServer) ListNodeTypes(context.Context, *Empty) (*NodeTypeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodeTypes not implemented")
}
func (UnimplementedSquillaHostServer) UpdateNodeType(context.Context, *UpdateNodeTypeRequest) (*NodeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNodeType not implemented")
}
func (UnimplementedSquillaHostServer) DeleteNodeType(context.Context, *DeleteNodeTypeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNodeType not implemented")
}
func (UnimplementedSquillaHostServer) mustEmbedUnimplementedSquillaHostServer() {}
func (UnimplementedSquillaHostServer) testEmbeddedByValue()                     {}

// UnsafeSquillaHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SquillaHostServer will
// result in compilation errors.
type UnsafeSquillaHostServer interface {
	mustEmbedUnimplementedSquillaHostServer()
}

func RegisterSquillaHostServer(s grpc.ServiceRegistrar, srv SquillaHostServer) {
	// If the following call panics, it indicates UnimplementedSquillaHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SquillaHost_ServiceDesc, srv)
}

func _SquillaHost_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_QueryNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).QueryNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_QueryNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).QueryNodes(ctx, req.(*QueryNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_ListTaxonomyTerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaxonomyTermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).ListTaxonomyTerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_ListTaxonomyTerms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).ListTaxonomyTerms(ctx, req.(*ListTaxonomyTermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_ListTerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).ListTerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_ListTerms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).ListTerms(ctx, req.(*ListTermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_GetTerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).GetTerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_GetTerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).GetTerm(ctx, req.(*GetTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_CreateTerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).CreateTerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_CreateTerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).CreateTerm(ctx, req.(*CreateTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_UpdateTerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).UpdateTerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_UpdateTerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).UpdateTerm(ctx, req.(*UpdateTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DeleteTerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DeleteTerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DeleteTerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DeleteTerm(ctx, req.(*DeleteTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_RegisterTaxonomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaxonomyInputMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).RegisterTaxonomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_RegisterTaxonomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).RegisterTaxonomy(ctx, req.(*TaxonomyInputMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_GetTaxonomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaxonomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).GetTaxonomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_GetTaxonomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).GetTaxonomy(ctx, req.(*GetTaxonomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_ListTaxonomies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).ListTaxonomies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_ListTaxonomies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).ListTaxonomies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_UpdateTaxonomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaxonomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).UpdateTaxonomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_UpdateTaxonomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).UpdateTaxonomy(ctx, req.(*UpdateTaxonomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DeleteTaxonomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaxonomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DeleteTaxonomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DeleteTaxonomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DeleteTaxonomy(ctx, req.(*DeleteTaxonomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_GetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).GetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_GetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).GetSetting(ctx, req.(*GetSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_SetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).SetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_SetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).SetSetting(ctx, req.(*SetSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_EmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).EmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_EmitEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).EmitEvent(ctx, req.(*EmitEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_GetMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).GetMenu(ctx, req.(*GetMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_GetMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).GetMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_GetMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).GetMenus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_QueryUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).QueryUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_QueryUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).QueryUsers(ctx, req.(*QueryUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DataGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DataGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DataGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DataGet(ctx, req.(*DataGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DataQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DataQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DataQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DataQuery(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DataCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DataCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DataCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DataCreate(ctx, req.(*DataCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DataUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DataUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DataUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DataUpdate(ctx, req.(*DataUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DataDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DataDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DataDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DataDelete(ctx, req.(*DataDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DataExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DataExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DataExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DataExec(ctx, req.(*DataExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_StoreFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).StoreFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_StoreFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).StoreFile(ctx, req.(*StoreFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_RegisterNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeTypeInputMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).RegisterNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_RegisterNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).RegisterNodeType(ctx, req.(*NodeTypeInputMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_GetNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).GetNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_GetNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).GetNodeType(ctx, req.(*GetNodeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_ListNodeTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).ListNodeTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_ListNodeTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).ListNodeTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_UpdateNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).UpdateNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_UpdateNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).UpdateNodeType(ctx, req.(*UpdateNodeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SquillaHost_DeleteNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SquillaHostServer).DeleteNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SquillaHost_DeleteNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SquillaHostServer).DeleteNodeType(ctx, req.(*DeleteNodeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SquillaHost_ServiceDesc is the grpc.ServiceDesc for SquillaHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SquillaHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "squilla.coreapi.SquillaHost",
	HandlerType: (*SquillaHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNode",
			Handler:    _SquillaHost_GetNode_Handler,
		},
		{
			MethodName: "QueryNodes",
			Handler:    _SquillaHost_QueryNodes_Handler,
		},
		{
			MethodName: "ListTaxonomyTerms",
			Handler:    _SquillaHost_ListTaxonomyTerms_Handler,
		},
		{
			MethodName: "CreateNode",
			Handler:    _SquillaHost_CreateNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _SquillaHost_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _SquillaHost_DeleteNode_Handler,
		},
		{
			MethodName: "ListTerms",
			Handler:    _SquillaHost_ListTerms_Handler,
		},
		{
			MethodName: "GetTerm",
			Handler:    _SquillaHost_GetTerm_Handler,
		},
		{
			MethodName: "CreateTerm",
			Handler:    _SquillaHost_CreateTerm_Handler,
		},
		{
			MethodName: "UpdateTerm",
			Handler:    _SquillaHost_UpdateTerm_Handler,
		},
		{
			MethodName: "DeleteTerm",
			Handler:    _SquillaHost_DeleteTerm_Handler,
		},
		{
			MethodName: "RegisterTaxonomy",
			Handler:    _SquillaHost_RegisterTaxonomy_Handler,
		},
		{
			MethodName: "GetTaxonomy",
			Handler:    _SquillaHost_GetTaxonomy_Handler,
		},
		{
			MethodName: "ListTaxonomies",
			Handler:    _SquillaHost_ListTaxonomies_Handler,
		},
		{
			MethodName: "UpdateTaxonomy",
			Handler:    _SquillaHost_UpdateTaxonomy_Handler,
		},
		{
			MethodName: "DeleteTaxonomy",
			Handler:    _SquillaHost_DeleteTaxonomy_Handler,
		},
		{
			MethodName: "GetSetting",
			Handler:    _SquillaHost_GetSetting_Handler,
		},
		{
			MethodName: "SetSetting",
			Handler:    _SquillaHost_SetSetting_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _SquillaHost_GetSettings_Handler,
		},
		{
			MethodName: "EmitEvent",
			Handler:    _SquillaHost_EmitEvent_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _SquillaHost_SendEmail_Handler,
		},
		{
			MethodName: "GetMenu",
			Handler:    _SquillaHost_GetMenu_Handler,
		},
		{
			MethodName: "GetMenus",
			Handler:    _SquillaHost_GetMenus_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _SquillaHost_GetUser_Handler,
		},
		{
			MethodName: "QueryUsers",
			Handler:    _SquillaHost_QueryUsers_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _SquillaHost_Fetch_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _SquillaHost_Log_Handler,
		},
		{
			MethodName: "DataGet",
			Handler:    _SquillaHost_DataGet_Handler,
		},
		{
			MethodName: "DataQuery",
			Handler:    _SquillaHost_DataQuery_Handler,
		},
		{
			MethodName: "DataCreate",
			Handler:    _SquillaHost_DataCreate_Handler,
		},
		{
			MethodName: "DataUpdate",
			Handler:    _SquillaHost_DataUpdate_Handler,
		},
		{
			MethodName: "DataDelete",
			Handler:    _SquillaHost_DataDelete_Handler,
		},
		{
			MethodName: "DataExec",
			Handler:    _SquillaHost_DataExec_Handler,
		},
		{
			MethodName: "StoreFile",
			Handler:    _SquillaHost_StoreFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _SquillaHost_DeleteFile_Handler,
		},
		{
			MethodName: "RegisterNodeType",
			Handler:    _SquillaHost_RegisterNodeType_Handler,
		},
		{
			MethodName: "GetNodeType",
			Handler:    _SquillaHost_GetNodeType_Handler,
		},
		{
			MethodName: "ListNodeTypes",
			Handler:    _SquillaHost_ListNodeTypes_Handler,
		},
		{
			MethodName: "UpdateNodeType",
			Handler:    _SquillaHost_UpdateNodeType_Handler,
		},
		{
			MethodName: "DeleteNodeType",
			Handler:    _SquillaHost_DeleteNodeType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coreapi/squilla_coreapi.proto",
}
