// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: vibecms_coreapi.proto

package coreapipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_vibecms_coreapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{0}
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type QueryNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ParentId      uint32                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	HasParentId   bool                   `protobuf:"varint,4,opt,name=has_parent_id,json=hasParentId,proto3" json:"has_parent_id,omitempty"`
	LanguageCode  string                 `protobuf:"bytes,5,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	Slug          string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	Search        string                 `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`
	Limit         int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy       string                 `protobuf:"bytes,10,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNodesRequest) Reset() {
	*x = QueryNodesRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodesRequest) ProtoMessage() {}

func (x *QueryNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodesRequest.ProtoReflect.Descriptor instead.
func (*QueryNodesRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{2}
}

func (x *QueryNodesRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *QueryNodesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryNodesRequest) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *QueryNodesRequest) GetHasParentId() bool {
	if x != nil {
		return x.HasParentId
	}
	return false
}

func (x *QueryNodesRequest) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *QueryNodesRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *QueryNodesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *QueryNodesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryNodesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryNodesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *NodeInput             `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNodeRequest) GetInput() *NodeInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type UpdateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         *NodeInput             `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeRequest) Reset() {
	*x = UpdateNodeRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRequest) ProtoMessage() {}

func (x *UpdateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNodeRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNodeRequest) GetInput() *NodeInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteNodeRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NodeInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ParentId       uint32                 `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	HasParentId    bool                   `protobuf:"varint,2,opt,name=has_parent_id,json=hasParentId,proto3" json:"has_parent_id,omitempty"`
	NodeType       string                 `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LanguageCode   string                 `protobuf:"bytes,5,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	Slug           string                 `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	Title          string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	BlocksDataJson string                 `protobuf:"bytes,8,opt,name=blocks_data_json,json=blocksDataJson,proto3" json:"blocks_data_json,omitempty"` // JSON-encoded
	FieldsDataJson string                 `protobuf:"bytes,9,opt,name=fields_data_json,json=fieldsDataJson,proto3" json:"fields_data_json,omitempty"` // JSON-encoded map[string]any
	SeoSettings    map[string]string      `protobuf:"bytes,10,rep,name=seo_settings,json=seoSettings,proto3" json:"seo_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeInput) Reset() {
	*x = NodeInput{}
	mi := &file_vibecms_coreapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInput) ProtoMessage() {}

func (x *NodeInput) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInput.ProtoReflect.Descriptor instead.
func (*NodeInput) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{6}
}

func (x *NodeInput) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *NodeInput) GetHasParentId() bool {
	if x != nil {
		return x.HasParentId
	}
	return false
}

func (x *NodeInput) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeInput) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeInput) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *NodeInput) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *NodeInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NodeInput) GetBlocksDataJson() string {
	if x != nil {
		return x.BlocksDataJson
	}
	return ""
}

func (x *NodeInput) GetFieldsDataJson() string {
	if x != nil {
		return x.FieldsDataJson
	}
	return ""
}

func (x *NodeInput) GetSeoSettings() map[string]string {
	if x != nil {
		return x.SeoSettings
	}
	return nil
}

type NodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeMessage           `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_vibecms_coreapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{7}
}

func (x *NodeResponse) GetNode() *NodeMessage {
	if x != nil {
		return x.Node
	}
	return nil
}

type QueryNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeMessage         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNodesResponse) Reset() {
	*x = QueryNodesResponse{}
	mi := &file_vibecms_coreapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNodesResponse) ProtoMessage() {}

func (x *QueryNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNodesResponse.ProtoReflect.Descriptor instead.
func (*QueryNodesResponse) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{8}
}

func (x *QueryNodesResponse) GetNodes() []*NodeMessage {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *QueryNodesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type NodeMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid           string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ParentId       uint32                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	HasParentId    bool                   `protobuf:"varint,4,opt,name=has_parent_id,json=hasParentId,proto3" json:"has_parent_id,omitempty"`
	NodeType       string                 `protobuf:"bytes,5,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	LanguageCode   string                 `protobuf:"bytes,7,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"`
	Slug           string                 `protobuf:"bytes,8,opt,name=slug,proto3" json:"slug,omitempty"`
	FullUrl        string                 `protobuf:"bytes,9,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
	Title          string                 `protobuf:"bytes,10,opt,name=title,proto3" json:"title,omitempty"`
	BlocksDataJson string                 `protobuf:"bytes,11,opt,name=blocks_data_json,json=blocksDataJson,proto3" json:"blocks_data_json,omitempty"` // JSON-encoded
	FieldsDataJson string                 `protobuf:"bytes,12,opt,name=fields_data_json,json=fieldsDataJson,proto3" json:"fields_data_json,omitempty"` // JSON-encoded map[string]any
	SeoSettings    map[string]string      `protobuf:"bytes,13,rep,name=seo_settings,json=seoSettings,proto3" json:"seo_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PublishedAt    string                 `protobuf:"bytes,14,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // RFC3339 or empty
	CreatedAt      string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`       // RFC3339
	UpdatedAt      string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`       // RFC3339
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_vibecms_coreapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{9}
}

func (x *NodeMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NodeMessage) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *NodeMessage) GetHasParentId() bool {
	if x != nil {
		return x.HasParentId
	}
	return false
}

func (x *NodeMessage) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeMessage) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *NodeMessage) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *NodeMessage) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *NodeMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NodeMessage) GetBlocksDataJson() string {
	if x != nil {
		return x.BlocksDataJson
	}
	return ""
}

func (x *NodeMessage) GetFieldsDataJson() string {
	if x != nil {
		return x.FieldsDataJson
	}
	return ""
}

func (x *NodeMessage) GetSeoSettings() map[string]string {
	if x != nil {
		return x.SeoSettings
	}
	return nil
}

func (x *NodeMessage) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *NodeMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NodeMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingRequest) Reset() {
	*x = GetSettingRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingRequest) ProtoMessage() {}

func (x *GetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingRequest.ProtoReflect.Descriptor instead.
func (*GetSettingRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{10}
}

func (x *GetSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingResponse) Reset() {
	*x = SettingResponse{}
	mi := &file_vibecms_coreapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingResponse) ProtoMessage() {}

func (x *SettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingResponse.ProtoReflect.Descriptor instead.
func (*SettingResponse) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{11}
}

func (x *SettingResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSettingRequest) Reset() {
	*x = SetSettingRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingRequest) ProtoMessage() {}

func (x *SetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingRequest.ProtoReflect.Descriptor instead.
func (*SetSettingRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{12}
}

func (x *SetSettingRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSettingRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{13}
}

func (x *GetSettingsRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type SettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      map[string]string      `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsResponse) Reset() {
	*x = SettingsResponse{}
	mi := &file_vibecms_coreapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsResponse) ProtoMessage() {}

func (x *SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsResponse.ProtoReflect.Descriptor instead.
func (*SettingsResponse) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{14}
}

func (x *SettingsResponse) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type EmitEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // JSON-encoded map[string]any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEventRequest) Reset() {
	*x = EmitEventRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEventRequest) ProtoMessage() {}

func (x *EmitEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEventRequest.ProtoReflect.Descriptor instead.
func (*EmitEventRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{15}
}

func (x *EmitEventRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EmitEventRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []string               `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Html          string                 `protobuf:"bytes,3,opt,name=html,proto3" json:"html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{16}
}

func (x *SendEmailRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{17}
}

func (x *GetMenuRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type MenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          *MenuMessage           `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuResponse) Reset() {
	*x = MenuResponse{}
	mi := &file_vibecms_coreapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuResponse) ProtoMessage() {}

func (x *MenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuResponse.ProtoReflect.Descriptor instead.
func (*MenuResponse) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{18}
}

func (x *MenuResponse) GetMenu() *MenuMessage {
	if x != nil {
		return x.Menu
	}
	return nil
}

type MenuListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menus         []*MenuMessage         `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuListResponse) Reset() {
	*x = MenuListResponse{}
	mi := &file_vibecms_coreapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuListResponse) ProtoMessage() {}

func (x *MenuListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuListResponse.ProtoReflect.Descriptor instead.
func (*MenuListResponse) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{19}
}

func (x *MenuListResponse) GetMenus() []*MenuMessage {
	if x != nil {
		return x.Menus
	}
	return nil
}

type MenuMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Items         []*MenuItemMessage     `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuMessage) Reset() {
	*x = MenuMessage{}
	mi := &file_vibecms_coreapi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuMessage) ProtoMessage() {}

func (x *MenuMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuMessage.ProtoReflect.Descriptor instead.
func (*MenuMessage) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{20}
}

func (x *MenuMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuMessage) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *MenuMessage) GetItems() []*MenuItemMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *MenuMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MenuMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MenuItemMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	ParentId      uint32                 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	HasParentId   bool                   `protobuf:"varint,6,opt,name=has_parent_id,json=hasParentId,proto3" json:"has_parent_id,omitempty"`
	Position      int32                  `protobuf:"varint,7,opt,name=position,proto3" json:"position,omitempty"`
	Children      []*MenuItemMessage     `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemMessage) Reset() {
	*x = MenuItemMessage{}
	mi := &file_vibecms_coreapi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemMessage) ProtoMessage() {}

func (x *MenuItemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemMessage.ProtoReflect.Descriptor instead.
func (*MenuItemMessage) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{21}
}

func (x *MenuItemMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuItemMessage) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MenuItemMessage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MenuItemMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MenuItemMessage) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *MenuItemMessage) GetHasParentId() bool {
	if x != nil {
		return x.HasParentId
	}
	return false
}

func (x *MenuItemMessage) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *MenuItemMessage) GetChildren() []*MenuItemMessage {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type QueryUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleSlug      string                 `protobuf:"bytes,1,opt,name=role_slug,json=roleSlug,proto3" json:"role_slug,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUsersRequest) Reset() {
	*x = QueryUsersRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsersRequest) ProtoMessage() {}

func (x *QueryUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsersRequest.ProtoReflect.Descriptor instead.
func (*QueryUsersRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{23}
}

func (x *QueryUsersRequest) GetRoleSlug() string {
	if x != nil {
		return x.RoleSlug
	}
	return ""
}

func (x *QueryUsersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *QueryUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserMessage           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_vibecms_coreapi_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{24}
}

func (x *UserResponse) GetUser() *UserMessage {
	if x != nil {
		return x.User
	}
	return nil
}

type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserMessage         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_vibecms_coreapi_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{25}
}

func (x *UserListResponse) GetUsers() []*UserMessage {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RoleId        uint32                 `protobuf:"varint,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	HasRoleId     bool                   `protobuf:"varint,5,opt,name=has_role_id,json=hasRoleId,proto3" json:"has_role_id,omitempty"`
	RoleSlug      string                 `protobuf:"bytes,6,opt,name=role_slug,json=roleSlug,proto3" json:"role_slug,omitempty"`
	LanguageId    int32                  `protobuf:"varint,7,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	HasLanguageId bool                   `protobuf:"varint,8,opt,name=has_language_id,json=hasLanguageId,proto3" json:"has_language_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_vibecms_coreapi_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{26}
}

func (x *UserMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMessage) GetRoleId() uint32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserMessage) GetHasRoleId() bool {
	if x != nil {
		return x.HasRoleId
	}
	return false
}

func (x *UserMessage) GetRoleSlug() string {
	if x != nil {
		return x.RoleSlug
	}
	return ""
}

func (x *UserMessage) GetLanguageId() int32 {
	if x != nil {
		return x.LanguageId
	}
	return 0
}

func (x *UserMessage) GetHasLanguageId() bool {
	if x != nil {
		return x.HasLanguageId
	}
	return false
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Timeout       int32                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{27}
}

func (x *FetchRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FetchRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *FetchRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_vibecms_coreapi_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{28}
}

func (x *FetchResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FetchResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *FetchResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FieldsJson    string                 `protobuf:"bytes,3,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"` // JSON-encoded map[string]any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_vibecms_coreapi_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vibecms_coreapi_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_vibecms_coreapi_proto_rawDescGZIP(), []int{29}
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRequest) GetFieldsJson() string {
	if x != nil {
		return x.FieldsJson
	}
	return ""
}

var File_vibecms_coreapi_proto protoreflect.FileDescriptor

const file_vibecms_coreapi_proto_rawDesc = "" +
	"\n" +
	"\x15vibecms_coreapi.proto\x12\x0fvibecms.coreapi\"\a\n" +
	"\x05Empty\" \n" +
	"\x0eGetNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xa3\x02\n" +
	"\x11QueryNodesRequest\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\rR\bparentId\x12\"\n" +
	"\rhas_parent_id\x18\x04 \x01(\bR\vhasParentId\x12#\n" +
	"\rlanguage_code\x18\x05 \x01(\tR\flanguageCode\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12\x16\n" +
	"\x06search\x18\a \x01(\tR\x06search\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\t \x01(\x05R\x06offset\x12\x19\n" +
	"\border_by\x18\n" +
	" \x01(\tR\aorderBy\"E\n" +
	"\x11CreateNodeRequest\x120\n" +
	"\x05input\x18\x01 \x01(\v2\x1a.vibecms.coreapi.NodeInputR\x05input\"U\n" +
	"\x11UpdateNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x120\n" +
	"\x05input\x18\x02 \x01(\v2\x1a.vibecms.coreapi.NodeInputR\x05input\"#\n" +
	"\x11DeleteNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xb4\x03\n" +
	"\tNodeInput\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\rR\bparentId\x12\"\n" +
	"\rhas_parent_id\x18\x02 \x01(\bR\vhasParentId\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rlanguage_code\x18\x05 \x01(\tR\flanguageCode\x12\x12\n" +
	"\x04slug\x18\x06 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12(\n" +
	"\x10blocks_data_json\x18\b \x01(\tR\x0eblocksDataJson\x12(\n" +
	"\x10fields_data_json\x18\t \x01(\tR\x0efieldsDataJson\x12N\n" +
	"\fseo_settings\x18\n" +
	" \x03(\v2+.vibecms.coreapi.NodeInput.SeoSettingsEntryR\vseoSettings\x1a>\n" +
	"\x10SeoSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\fNodeResponse\x120\n" +
	"\x04node\x18\x01 \x01(\v2\x1c.vibecms.coreapi.NodeMessageR\x04node\"^\n" +
	"\x12QueryNodesResponse\x122\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.vibecms.coreapi.NodeMessageR\x05nodes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xd8\x04\n" +
	"\vNodeMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\rR\bparentId\x12\"\n" +
	"\rhas_parent_id\x18\x04 \x01(\bR\vhasParentId\x12\x1b\n" +
	"\tnode_type\x18\x05 \x01(\tR\bnodeType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rlanguage_code\x18\a \x01(\tR\flanguageCode\x12\x12\n" +
	"\x04slug\x18\b \x01(\tR\x04slug\x12\x19\n" +
	"\bfull_url\x18\t \x01(\tR\afullUrl\x12\x14\n" +
	"\x05title\x18\n" +
	" \x01(\tR\x05title\x12(\n" +
	"\x10blocks_data_json\x18\v \x01(\tR\x0eblocksDataJson\x12(\n" +
	"\x10fields_data_json\x18\f \x01(\tR\x0efieldsDataJson\x12P\n" +
	"\fseo_settings\x18\r \x03(\v2-.vibecms.coreapi.NodeMessage.SeoSettingsEntryR\vseoSettings\x12!\n" +
	"\fpublished_at\x18\x0e \x01(\tR\vpublishedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\x1a>\n" +
	"\x10SeoSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\x11GetSettingRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\x0fSettingResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\";\n" +
	"\x11SetSettingRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\",\n" +
	"\x12GetSettingsRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"\x9c\x01\n" +
	"\x10SettingsResponse\x12K\n" +
	"\bsettings\x18\x01 \x03(\v2/.vibecms.coreapi.SettingsResponse.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x10EmitEventRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"P\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x03(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04html\x18\x03 \x01(\tR\x04html\"$\n" +
	"\x0eGetMenuRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"@\n" +
	"\fMenuResponse\x120\n" +
	"\x04menu\x18\x01 \x01(\v2\x1c.vibecms.coreapi.MenuMessageR\x04menu\"F\n" +
	"\x10MenuListResponse\x122\n" +
	"\x05menus\x18\x01 \x03(\v2\x1c.vibecms.coreapi.MenuMessageR\x05menus\"\xbb\x01\n" +
	"\vMenuMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x126\n" +
	"\x05items\x18\x04 \x03(\v2 .vibecms.coreapi.MenuItemMessageR\x05items\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xfc\x01\n" +
	"\x0fMenuItemMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\rR\bparentId\x12\"\n" +
	"\rhas_parent_id\x18\x06 \x01(\bR\vhasParentId\x12\x1a\n" +
	"\bposition\x18\a \x01(\x05R\bposition\x12<\n" +
	"\bchildren\x18\b \x03(\v2 .vibecms.coreapi.MenuItemMessageR\bchildren\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"v\n" +
	"\x11QueryUsersRequest\x12\x1b\n" +
	"\trole_slug\x18\x01 \x01(\tR\broleSlug\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"@\n" +
	"\fUserResponse\x120\n" +
	"\x04user\x18\x01 \x01(\v2\x1c.vibecms.coreapi.UserMessageR\x04user\"F\n" +
	"\x10UserListResponse\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.vibecms.coreapi.UserMessageR\x05users\"\xe6\x01\n" +
	"\vUserMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\rR\x06roleId\x12\x1e\n" +
	"\vhas_role_id\x18\x05 \x01(\bR\thasRoleId\x12\x1b\n" +
	"\trole_slug\x18\x06 \x01(\tR\broleSlug\x12\x1f\n" +
	"\vlanguage_id\x18\a \x01(\x05R\n" +
	"languageId\x12&\n" +
	"\x0fhas_language_id\x18\b \x01(\bR\rhasLanguageId\"\xe8\x01\n" +
	"\fFetchRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12D\n" +
	"\aheaders\x18\x03 \x03(\v2*.vibecms.coreapi.FetchRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x05R\atimeout\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\rFetchResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12E\n" +
	"\aheaders\x18\x02 \x03(\v2+.vibecms.coreapi.FetchResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vfields_json\x18\x03 \x01(\tR\n" +
	"fieldsJson2\xd6\t\n" +
	"\vVibeCMSHost\x12I\n" +
	"\aGetNode\x12\x1f.vibecms.coreapi.GetNodeRequest\x1a\x1d.vibecms.coreapi.NodeResponse\x12U\n" +
	"\n" +
	"QueryNodes\x12\".vibecms.coreapi.QueryNodesRequest\x1a#.vibecms.coreapi.QueryNodesResponse\x12O\n" +
	"\n" +
	"CreateNode\x12\".vibecms.coreapi.CreateNodeRequest\x1a\x1d.vibecms.coreapi.NodeResponse\x12O\n" +
	"\n" +
	"UpdateNode\x12\".vibecms.coreapi.UpdateNodeRequest\x1a\x1d.vibecms.coreapi.NodeResponse\x12H\n" +
	"\n" +
	"DeleteNode\x12\".vibecms.coreapi.DeleteNodeRequest\x1a\x16.vibecms.coreapi.Empty\x12R\n" +
	"\n" +
	"GetSetting\x12\".vibecms.coreapi.GetSettingRequest\x1a .vibecms.coreapi.SettingResponse\x12H\n" +
	"\n" +
	"SetSetting\x12\".vibecms.coreapi.SetSettingRequest\x1a\x16.vibecms.coreapi.Empty\x12U\n" +
	"\vGetSettings\x12#.vibecms.coreapi.GetSettingsRequest\x1a!.vibecms.coreapi.SettingsResponse\x12F\n" +
	"\tEmitEvent\x12!.vibecms.coreapi.EmitEventRequest\x1a\x16.vibecms.coreapi.Empty\x12F\n" +
	"\tSendEmail\x12!.vibecms.coreapi.SendEmailRequest\x1a\x16.vibecms.coreapi.Empty\x12I\n" +
	"\aGetMenu\x12\x1f.vibecms.coreapi.GetMenuRequest\x1a\x1d.vibecms.coreapi.MenuResponse\x12E\n" +
	"\bGetMenus\x12\x16.vibecms.coreapi.Empty\x1a!.vibecms.coreapi.MenuListResponse\x12I\n" +
	"\aGetUser\x12\x1f.vibecms.coreapi.GetUserRequest\x1a\x1d.vibecms.coreapi.UserResponse\x12S\n" +
	"\n" +
	"QueryUsers\x12\".vibecms.coreapi.QueryUsersRequest\x1a!.vibecms.coreapi.UserListResponse\x12F\n" +
	"\x05Fetch\x12\x1d.vibecms.coreapi.FetchRequest\x1a\x1e.vibecms.coreapi.FetchResponse\x12:\n" +
	"\x03Log\x12\x1b.vibecms.coreapi.LogRequest\x1a\x16.vibecms.coreapi.EmptyB\x1eZ\x1cvibecms/pkg/plugin/coreapipbb\x06proto3"

var (
	file_vibecms_coreapi_proto_rawDescOnce sync.Once
	file_vibecms_coreapi_proto_rawDescData []byte
)

func file_vibecms_coreapi_proto_rawDescGZIP() []byte {
	file_vibecms_coreapi_proto_rawDescOnce.Do(func() {
		file_vibecms_coreapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vibecms_coreapi_proto_rawDesc), len(file_vibecms_coreapi_proto_rawDesc)))
	})
	return file_vibecms_coreapi_proto_rawDescData
}

var file_vibecms_coreapi_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_vibecms_coreapi_proto_goTypes = []any{
	(*Empty)(nil),              // 0: vibecms.coreapi.Empty
	(*GetNodeRequest)(nil),     // 1: vibecms.coreapi.GetNodeRequest
	(*QueryNodesRequest)(nil),  // 2: vibecms.coreapi.QueryNodesRequest
	(*CreateNodeRequest)(nil),  // 3: vibecms.coreapi.CreateNodeRequest
	(*UpdateNodeRequest)(nil),  // 4: vibecms.coreapi.UpdateNodeRequest
	(*DeleteNodeRequest)(nil),  // 5: vibecms.coreapi.DeleteNodeRequest
	(*NodeInput)(nil),          // 6: vibecms.coreapi.NodeInput
	(*NodeResponse)(nil),       // 7: vibecms.coreapi.NodeResponse
	(*QueryNodesResponse)(nil), // 8: vibecms.coreapi.QueryNodesResponse
	(*NodeMessage)(nil),        // 9: vibecms.coreapi.NodeMessage
	(*GetSettingRequest)(nil),  // 10: vibecms.coreapi.GetSettingRequest
	(*SettingResponse)(nil),    // 11: vibecms.coreapi.SettingResponse
	(*SetSettingRequest)(nil),  // 12: vibecms.coreapi.SetSettingRequest
	(*GetSettingsRequest)(nil), // 13: vibecms.coreapi.GetSettingsRequest
	(*SettingsResponse)(nil),   // 14: vibecms.coreapi.SettingsResponse
	(*EmitEventRequest)(nil),   // 15: vibecms.coreapi.EmitEventRequest
	(*SendEmailRequest)(nil),   // 16: vibecms.coreapi.SendEmailRequest
	(*GetMenuRequest)(nil),     // 17: vibecms.coreapi.GetMenuRequest
	(*MenuResponse)(nil),       // 18: vibecms.coreapi.MenuResponse
	(*MenuListResponse)(nil),   // 19: vibecms.coreapi.MenuListResponse
	(*MenuMessage)(nil),        // 20: vibecms.coreapi.MenuMessage
	(*MenuItemMessage)(nil),    // 21: vibecms.coreapi.MenuItemMessage
	(*GetUserRequest)(nil),     // 22: vibecms.coreapi.GetUserRequest
	(*QueryUsersRequest)(nil),  // 23: vibecms.coreapi.QueryUsersRequest
	(*UserResponse)(nil),       // 24: vibecms.coreapi.UserResponse
	(*UserListResponse)(nil),   // 25: vibecms.coreapi.UserListResponse
	(*UserMessage)(nil),        // 26: vibecms.coreapi.UserMessage
	(*FetchRequest)(nil),       // 27: vibecms.coreapi.FetchRequest
	(*FetchResponse)(nil),      // 28: vibecms.coreapi.FetchResponse
	(*LogRequest)(nil),         // 29: vibecms.coreapi.LogRequest
	nil,                        // 30: vibecms.coreapi.NodeInput.SeoSettingsEntry
	nil,                        // 31: vibecms.coreapi.NodeMessage.SeoSettingsEntry
	nil,                        // 32: vibecms.coreapi.SettingsResponse.SettingsEntry
	nil,                        // 33: vibecms.coreapi.FetchRequest.HeadersEntry
	nil,                        // 34: vibecms.coreapi.FetchResponse.HeadersEntry
}
var file_vibecms_coreapi_proto_depIdxs = []int32{
	6,  // 0: vibecms.coreapi.CreateNodeRequest.input:type_name -> vibecms.coreapi.NodeInput
	6,  // 1: vibecms.coreapi.UpdateNodeRequest.input:type_name -> vibecms.coreapi.NodeInput
	30, // 2: vibecms.coreapi.NodeInput.seo_settings:type_name -> vibecms.coreapi.NodeInput.SeoSettingsEntry
	9,  // 3: vibecms.coreapi.NodeResponse.node:type_name -> vibecms.coreapi.NodeMessage
	9,  // 4: vibecms.coreapi.QueryNodesResponse.nodes:type_name -> vibecms.coreapi.NodeMessage
	31, // 5: vibecms.coreapi.NodeMessage.seo_settings:type_name -> vibecms.coreapi.NodeMessage.SeoSettingsEntry
	32, // 6: vibecms.coreapi.SettingsResponse.settings:type_name -> vibecms.coreapi.SettingsResponse.SettingsEntry
	20, // 7: vibecms.coreapi.MenuResponse.menu:type_name -> vibecms.coreapi.MenuMessage
	20, // 8: vibecms.coreapi.MenuListResponse.menus:type_name -> vibecms.coreapi.MenuMessage
	21, // 9: vibecms.coreapi.MenuMessage.items:type_name -> vibecms.coreapi.MenuItemMessage
	21, // 10: vibecms.coreapi.MenuItemMessage.children:type_name -> vibecms.coreapi.MenuItemMessage
	26, // 11: vibecms.coreapi.UserResponse.user:type_name -> vibecms.coreapi.UserMessage
	26, // 12: vibecms.coreapi.UserListResponse.users:type_name -> vibecms.coreapi.UserMessage
	33, // 13: vibecms.coreapi.FetchRequest.headers:type_name -> vibecms.coreapi.FetchRequest.HeadersEntry
	34, // 14: vibecms.coreapi.FetchResponse.headers:type_name -> vibecms.coreapi.FetchResponse.HeadersEntry
	1,  // 15: vibecms.coreapi.VibeCMSHost.GetNode:input_type -> vibecms.coreapi.GetNodeRequest
	2,  // 16: vibecms.coreapi.VibeCMSHost.QueryNodes:input_type -> vibecms.coreapi.QueryNodesRequest
	3,  // 17: vibecms.coreapi.VibeCMSHost.CreateNode:input_type -> vibecms.coreapi.CreateNodeRequest
	4,  // 18: vibecms.coreapi.VibeCMSHost.UpdateNode:input_type -> vibecms.coreapi.UpdateNodeRequest
	5,  // 19: vibecms.coreapi.VibeCMSHost.DeleteNode:input_type -> vibecms.coreapi.DeleteNodeRequest
	10, // 20: vibecms.coreapi.VibeCMSHost.GetSetting:input_type -> vibecms.coreapi.GetSettingRequest
	12, // 21: vibecms.coreapi.VibeCMSHost.SetSetting:input_type -> vibecms.coreapi.SetSettingRequest
	13, // 22: vibecms.coreapi.VibeCMSHost.GetSettings:input_type -> vibecms.coreapi.GetSettingsRequest
	15, // 23: vibecms.coreapi.VibeCMSHost.EmitEvent:input_type -> vibecms.coreapi.EmitEventRequest
	16, // 24: vibecms.coreapi.VibeCMSHost.SendEmail:input_type -> vibecms.coreapi.SendEmailRequest
	17, // 25: vibecms.coreapi.VibeCMSHost.GetMenu:input_type -> vibecms.coreapi.GetMenuRequest
	0,  // 26: vibecms.coreapi.VibeCMSHost.GetMenus:input_type -> vibecms.coreapi.Empty
	22, // 27: vibecms.coreapi.VibeCMSHost.GetUser:input_type -> vibecms.coreapi.GetUserRequest
	23, // 28: vibecms.coreapi.VibeCMSHost.QueryUsers:input_type -> vibecms.coreapi.QueryUsersRequest
	27, // 29: vibecms.coreapi.VibeCMSHost.Fetch:input_type -> vibecms.coreapi.FetchRequest
	29, // 30: vibecms.coreapi.VibeCMSHost.Log:input_type -> vibecms.coreapi.LogRequest
	7,  // 31: vibecms.coreapi.VibeCMSHost.GetNode:output_type -> vibecms.coreapi.NodeResponse
	8,  // 32: vibecms.coreapi.VibeCMSHost.QueryNodes:output_type -> vibecms.coreapi.QueryNodesResponse
	7,  // 33: vibecms.coreapi.VibeCMSHost.CreateNode:output_type -> vibecms.coreapi.NodeResponse
	7,  // 34: vibecms.coreapi.VibeCMSHost.UpdateNode:output_type -> vibecms.coreapi.NodeResponse
	0,  // 35: vibecms.coreapi.VibeCMSHost.DeleteNode:output_type -> vibecms.coreapi.Empty
	11, // 36: vibecms.coreapi.VibeCMSHost.GetSetting:output_type -> vibecms.coreapi.SettingResponse
	0,  // 37: vibecms.coreapi.VibeCMSHost.SetSetting:output_type -> vibecms.coreapi.Empty
	14, // 38: vibecms.coreapi.VibeCMSHost.GetSettings:output_type -> vibecms.coreapi.SettingsResponse
	0,  // 39: vibecms.coreapi.VibeCMSHost.EmitEvent:output_type -> vibecms.coreapi.Empty
	0,  // 40: vibecms.coreapi.VibeCMSHost.SendEmail:output_type -> vibecms.coreapi.Empty
	18, // 41: vibecms.coreapi.VibeCMSHost.GetMenu:output_type -> vibecms.coreapi.MenuResponse
	19, // 42: vibecms.coreapi.VibeCMSHost.GetMenus:output_type -> vibecms.coreapi.MenuListResponse
	24, // 43: vibecms.coreapi.VibeCMSHost.GetUser:output_type -> vibecms.coreapi.UserResponse
	25, // 44: vibecms.coreapi.VibeCMSHost.QueryUsers:output_type -> vibecms.coreapi.UserListResponse
	28, // 45: vibecms.coreapi.VibeCMSHost.Fetch:output_type -> vibecms.coreapi.FetchResponse
	0,  // 46: vibecms.coreapi.VibeCMSHost.Log:output_type -> vibecms.coreapi.Empty
	31, // [31:47] is the sub-list for method output_type
	15, // [15:31] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_vibecms_coreapi_proto_init() }
func file_vibecms_coreapi_proto_init() {
	if File_vibecms_coreapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vibecms_coreapi_proto_rawDesc), len(file_vibecms_coreapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vibecms_coreapi_proto_goTypes,
		DependencyIndexes: file_vibecms_coreapi_proto_depIdxs,
		MessageInfos:      file_vibecms_coreapi_proto_msgTypes,
	}.Build()
	File_vibecms_coreapi_proto = out.File
	file_vibecms_coreapi_proto_goTypes = nil
	file_vibecms_coreapi_proto_depIdxs = nil
}
