// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: vibecms_coreapi.proto

package coreapipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VibeCMSHost_GetNode_FullMethodName           = "/vibecms.coreapi.VibeCMSHost/GetNode"
	VibeCMSHost_QueryNodes_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/QueryNodes"
	VibeCMSHost_ListTaxonomyTerms_FullMethodName = "/vibecms.coreapi.VibeCMSHost/ListTaxonomyTerms"
	VibeCMSHost_CreateNode_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/CreateNode"
	VibeCMSHost_UpdateNode_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/UpdateNode"
	VibeCMSHost_DeleteNode_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/DeleteNode"
	VibeCMSHost_ListTerms_FullMethodName         = "/vibecms.coreapi.VibeCMSHost/ListTerms"
	VibeCMSHost_GetTerm_FullMethodName           = "/vibecms.coreapi.VibeCMSHost/GetTerm"
	VibeCMSHost_CreateTerm_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/CreateTerm"
	VibeCMSHost_UpdateTerm_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/UpdateTerm"
	VibeCMSHost_DeleteTerm_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/DeleteTerm"
	VibeCMSHost_RegisterTaxonomy_FullMethodName  = "/vibecms.coreapi.VibeCMSHost/RegisterTaxonomy"
	VibeCMSHost_GetTaxonomy_FullMethodName       = "/vibecms.coreapi.VibeCMSHost/GetTaxonomy"
	VibeCMSHost_ListTaxonomies_FullMethodName    = "/vibecms.coreapi.VibeCMSHost/ListTaxonomies"
	VibeCMSHost_UpdateTaxonomy_FullMethodName    = "/vibecms.coreapi.VibeCMSHost/UpdateTaxonomy"
	VibeCMSHost_DeleteTaxonomy_FullMethodName    = "/vibecms.coreapi.VibeCMSHost/DeleteTaxonomy"
	VibeCMSHost_GetSetting_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/GetSetting"
	VibeCMSHost_SetSetting_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/SetSetting"
	VibeCMSHost_GetSettings_FullMethodName       = "/vibecms.coreapi.VibeCMSHost/GetSettings"
	VibeCMSHost_EmitEvent_FullMethodName         = "/vibecms.coreapi.VibeCMSHost/EmitEvent"
	VibeCMSHost_SendEmail_FullMethodName         = "/vibecms.coreapi.VibeCMSHost/SendEmail"
	VibeCMSHost_GetMenu_FullMethodName           = "/vibecms.coreapi.VibeCMSHost/GetMenu"
	VibeCMSHost_GetMenus_FullMethodName          = "/vibecms.coreapi.VibeCMSHost/GetMenus"
	VibeCMSHost_GetUser_FullMethodName           = "/vibecms.coreapi.VibeCMSHost/GetUser"
	VibeCMSHost_QueryUsers_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/QueryUsers"
	VibeCMSHost_Fetch_FullMethodName             = "/vibecms.coreapi.VibeCMSHost/Fetch"
	VibeCMSHost_Log_FullMethodName               = "/vibecms.coreapi.VibeCMSHost/Log"
	VibeCMSHost_DataGet_FullMethodName           = "/vibecms.coreapi.VibeCMSHost/DataGet"
	VibeCMSHost_DataQuery_FullMethodName         = "/vibecms.coreapi.VibeCMSHost/DataQuery"
	VibeCMSHost_DataCreate_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/DataCreate"
	VibeCMSHost_DataUpdate_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/DataUpdate"
	VibeCMSHost_DataDelete_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/DataDelete"
	VibeCMSHost_DataExec_FullMethodName          = "/vibecms.coreapi.VibeCMSHost/DataExec"
	VibeCMSHost_StoreFile_FullMethodName         = "/vibecms.coreapi.VibeCMSHost/StoreFile"
	VibeCMSHost_DeleteFile_FullMethodName        = "/vibecms.coreapi.VibeCMSHost/DeleteFile"
	VibeCMSHost_RegisterNodeType_FullMethodName  = "/vibecms.coreapi.VibeCMSHost/RegisterNodeType"
	VibeCMSHost_GetNodeType_FullMethodName       = "/vibecms.coreapi.VibeCMSHost/GetNodeType"
	VibeCMSHost_ListNodeTypes_FullMethodName     = "/vibecms.coreapi.VibeCMSHost/ListNodeTypes"
	VibeCMSHost_UpdateNodeType_FullMethodName    = "/vibecms.coreapi.VibeCMSHost/UpdateNodeType"
	VibeCMSHost_DeleteNodeType_FullMethodName    = "/vibecms.coreapi.VibeCMSHost/DeleteNodeType"
)

// VibeCMSHostClient is the client API for VibeCMSHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VibeCMSHostClient interface {
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	QueryNodes(ctx context.Context, in *QueryNodesRequest, opts ...grpc.CallOption) (*QueryNodesResponse, error)
	ListTaxonomyTerms(ctx context.Context, in *ListTaxonomyTermsRequest, opts ...grpc.CallOption) (*ListTaxonomyTermsResponse, error)
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*Empty, error)
	// Taxonomies
	ListTerms(ctx context.Context, in *ListTermsRequest, opts ...grpc.CallOption) (*ListTermsResponse, error)
	GetTerm(ctx context.Context, in *GetTermRequest, opts ...grpc.CallOption) (*TermResponse, error)
	CreateTerm(ctx context.Context, in *CreateTermRequest, opts ...grpc.CallOption) (*TermResponse, error)
	UpdateTerm(ctx context.Context, in *UpdateTermRequest, opts ...grpc.CallOption) (*TermResponse, error)
	DeleteTerm(ctx context.Context, in *DeleteTermRequest, opts ...grpc.CallOption) (*Empty, error)
	// Taxonomy Definitions
	RegisterTaxonomy(ctx context.Context, in *TaxonomyInputMessage, opts ...grpc.CallOption) (*TaxonomyResponse, error)
	GetTaxonomy(ctx context.Context, in *GetTaxonomyRequest, opts ...grpc.CallOption) (*TaxonomyResponse, error)
	ListTaxonomies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaxonomyListResponse, error)
	UpdateTaxonomy(ctx context.Context, in *UpdateTaxonomyRequest, opts ...grpc.CallOption) (*TaxonomyResponse, error)
	DeleteTaxonomy(ctx context.Context, in *DeleteTaxonomyRequest, opts ...grpc.CallOption) (*Empty, error)
	GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*SettingResponse, error)
	SetSetting(ctx context.Context, in *SetSettingRequest, opts ...grpc.CallOption) (*Empty, error)
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error)
	EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*Empty, error)
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*Empty, error)
	GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*MenuResponse, error)
	GetMenus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	QueryUsers(ctx context.Context, in *QueryUsersRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error)
	DataGet(ctx context.Context, in *DataGetRequest, opts ...grpc.CallOption) (*DataRowResponse, error)
	DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
	DataCreate(ctx context.Context, in *DataCreateRequest, opts ...grpc.CallOption) (*DataRowResponse, error)
	DataUpdate(ctx context.Context, in *DataUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	DataDelete(ctx context.Context, in *DataDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	DataExec(ctx context.Context, in *DataExecRequest, opts ...grpc.CallOption) (*DataExecResponse, error)
	StoreFile(ctx context.Context, in *StoreFileRequest, opts ...grpc.CallOption) (*StoreFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*Empty, error)
	RegisterNodeType(ctx context.Context, in *NodeTypeInputMessage, opts ...grpc.CallOption) (*NodeTypeResponse, error)
	GetNodeType(ctx context.Context, in *GetNodeTypeRequest, opts ...grpc.CallOption) (*NodeTypeResponse, error)
	ListNodeTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeTypeListResponse, error)
	UpdateNodeType(ctx context.Context, in *UpdateNodeTypeRequest, opts ...grpc.CallOption) (*NodeTypeResponse, error)
	DeleteNodeType(ctx context.Context, in *DeleteNodeTypeRequest, opts ...grpc.CallOption) (*Empty, error)
}

type vibeCMSHostClient struct {
	cc grpc.ClientConnInterface
}

func NewVibeCMSHostClient(cc grpc.ClientConnInterface) VibeCMSHostClient {
	return &vibeCMSHostClient{cc}
}

func (c *vibeCMSHostClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) QueryNodes(ctx context.Context, in *QueryNodesRequest, opts ...grpc.CallOption) (*QueryNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryNodesResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_QueryNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) ListTaxonomyTerms(ctx context.Context, in *ListTaxonomyTermsRequest, opts ...grpc.CallOption) (*ListTaxonomyTermsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaxonomyTermsResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_ListTaxonomyTerms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) ListTerms(ctx context.Context, in *ListTermsRequest, opts ...grpc.CallOption) (*ListTermsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTermsResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_ListTerms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) GetTerm(ctx context.Context, in *GetTermRequest, opts ...grpc.CallOption) (*TermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TermResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_GetTerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) CreateTerm(ctx context.Context, in *CreateTermRequest, opts ...grpc.CallOption) (*TermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TermResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_CreateTerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) UpdateTerm(ctx context.Context, in *UpdateTermRequest, opts ...grpc.CallOption) (*TermResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TermResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_UpdateTerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DeleteTerm(ctx context.Context, in *DeleteTermRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_DeleteTerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) RegisterTaxonomy(ctx context.Context, in *TaxonomyInputMessage, opts ...grpc.CallOption) (*TaxonomyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaxonomyResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_RegisterTaxonomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) GetTaxonomy(ctx context.Context, in *GetTaxonomyRequest, opts ...grpc.CallOption) (*TaxonomyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaxonomyResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_GetTaxonomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) ListTaxonomies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaxonomyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaxonomyListResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_ListTaxonomies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) UpdateTaxonomy(ctx context.Context, in *UpdateTaxonomyRequest, opts ...grpc.CallOption) (*TaxonomyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaxonomyResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_UpdateTaxonomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DeleteTaxonomy(ctx context.Context, in *DeleteTaxonomyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_DeleteTaxonomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*SettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_GetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) SetSetting(ctx context.Context, in *SetSettingRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_SetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_EmitEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*MenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_GetMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) GetMenus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuListResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_GetMenus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) QueryUsers(ctx context.Context, in *QueryUsersRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_QueryUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DataGet(ctx context.Context, in *DataGetRequest, opts ...grpc.CallOption) (*DataRowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataRowResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_DataGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_DataQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DataCreate(ctx context.Context, in *DataCreateRequest, opts ...grpc.CallOption) (*DataRowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataRowResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_DataCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DataUpdate(ctx context.Context, in *DataUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_DataUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DataDelete(ctx context.Context, in *DataDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_DataDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DataExec(ctx context.Context, in *DataExecRequest, opts ...grpc.CallOption) (*DataExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataExecResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_DataExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) StoreFile(ctx context.Context, in *StoreFileRequest, opts ...grpc.CallOption) (*StoreFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreFileResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_StoreFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) RegisterNodeType(ctx context.Context, in *NodeTypeInputMessage, opts ...grpc.CallOption) (*NodeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeTypeResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_RegisterNodeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) GetNodeType(ctx context.Context, in *GetNodeTypeRequest, opts ...grpc.CallOption) (*NodeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeTypeResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_GetNodeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) ListNodeTypes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeTypeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeTypeListResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_ListNodeTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) UpdateNodeType(ctx context.Context, in *UpdateNodeTypeRequest, opts ...grpc.CallOption) (*NodeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeTypeResponse)
	err := c.cc.Invoke(ctx, VibeCMSHost_UpdateNodeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vibeCMSHostClient) DeleteNodeType(ctx context.Context, in *DeleteNodeTypeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, VibeCMSHost_DeleteNodeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VibeCMSHostServer is the server API for VibeCMSHost service.
// All implementations must embed UnimplementedVibeCMSHostServer
// for forward compatibility.
type VibeCMSHostServer interface {
	GetNode(context.Context, *GetNodeRequest) (*NodeResponse, error)
	QueryNodes(context.Context, *QueryNodesRequest) (*QueryNodesResponse, error)
	ListTaxonomyTerms(context.Context, *ListTaxonomyTermsRequest) (*ListTaxonomyTermsResponse, error)
	CreateNode(context.Context, *CreateNodeRequest) (*NodeResponse, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*NodeResponse, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*Empty, error)
	// Taxonomies
	ListTerms(context.Context, *ListTermsRequest) (*ListTermsResponse, error)
	GetTerm(context.Context, *GetTermRequest) (*TermResponse, error)
	CreateTerm(context.Context, *CreateTermRequest) (*TermResponse, error)
	UpdateTerm(context.Context, *UpdateTermRequest) (*TermResponse, error)
	DeleteTerm(context.Context, *DeleteTermRequest) (*Empty, error)
	// Taxonomy Definitions
	RegisterTaxonomy(context.Context, *TaxonomyInputMessage) (*TaxonomyResponse, error)
	GetTaxonomy(context.Context, *GetTaxonomyRequest) (*TaxonomyResponse, error)
	ListTaxonomies(context.Context, *Empty) (*TaxonomyListResponse, error)
	UpdateTaxonomy(context.Context, *UpdateTaxonomyRequest) (*TaxonomyResponse, error)
	DeleteTaxonomy(context.Context, *DeleteTaxonomyRequest) (*Empty, error)
	GetSetting(context.Context, *GetSettingRequest) (*SettingResponse, error)
	SetSetting(context.Context, *SetSettingRequest) (*Empty, error)
	GetSettings(context.Context, *GetSettingsRequest) (*SettingsResponse, error)
	EmitEvent(context.Context, *EmitEventRequest) (*Empty, error)
	SendEmail(context.Context, *SendEmailRequest) (*Empty, error)
	GetMenu(context.Context, *GetMenuRequest) (*MenuResponse, error)
	GetMenus(context.Context, *Empty) (*MenuListResponse, error)
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	QueryUsers(context.Context, *QueryUsersRequest) (*UserListResponse, error)
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	Log(context.Context, *LogRequest) (*Empty, error)
	DataGet(context.Context, *DataGetRequest) (*DataRowResponse, error)
	DataQuery(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
	DataCreate(context.Context, *DataCreateRequest) (*DataRowResponse, error)
	DataUpdate(context.Context, *DataUpdateRequest) (*Empty, error)
	DataDelete(context.Context, *DataDeleteRequest) (*Empty, error)
	DataExec(context.Context, *DataExecRequest) (*DataExecResponse, error)
	StoreFile(context.Context, *StoreFileRequest) (*StoreFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*Empty, error)
	RegisterNodeType(context.Context, *NodeTypeInputMessage) (*NodeTypeResponse, error)
	GetNodeType(context.Context, *GetNodeTypeRequest) (*NodeTypeResponse, error)
	ListNodeTypes(context.Context, *Empty) (*NodeTypeListResponse, error)
	UpdateNodeType(context.Context, *UpdateNodeTypeRequest) (*NodeTypeResponse, error)
	DeleteNodeType(context.Context, *DeleteNodeTypeRequest) (*Empty, error)
	mustEmbedUnimplementedVibeCMSHostServer()
}

// UnimplementedVibeCMSHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVibeCMSHostServer struct{}

func (UnimplementedVibeCMSHostServer) GetNode(context.Context, *GetNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedVibeCMSHostServer) QueryNodes(context.Context, *QueryNodesRequest) (*QueryNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryNodes not implemented")
}
func (UnimplementedVibeCMSHostServer) ListTaxonomyTerms(context.Context, *ListTaxonomyTermsRequest) (*ListTaxonomyTermsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaxonomyTerms not implemented")
}
func (UnimplementedVibeCMSHostServer) CreateNode(context.Context, *CreateNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedVibeCMSHostServer) UpdateNode(context.Context, *UpdateNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedVibeCMSHostServer) DeleteNode(context.Context, *DeleteNodeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedVibeCMSHostServer) ListTerms(context.Context, *ListTermsRequest) (*ListTermsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTerms not implemented")
}
func (UnimplementedVibeCMSHostServer) GetTerm(context.Context, *GetTermRequest) (*TermResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTerm not implemented")
}
func (UnimplementedVibeCMSHostServer) CreateTerm(context.Context, *CreateTermRequest) (*TermResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTerm not implemented")
}
func (UnimplementedVibeCMSHostServer) UpdateTerm(context.Context, *UpdateTermRequest) (*TermResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTerm not implemented")
}
func (UnimplementedVibeCMSHostServer) DeleteTerm(context.Context, *DeleteTermRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTerm not implemented")
}
func (UnimplementedVibeCMSHostServer) RegisterTaxonomy(context.Context, *TaxonomyInputMessage) (*TaxonomyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTaxonomy not implemented")
}
func (UnimplementedVibeCMSHostServer) GetTaxonomy(context.Context, *GetTaxonomyRequest) (*TaxonomyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaxonomy not implemented")
}
func (UnimplementedVibeCMSHostServer) ListTaxonomies(context.Context, *Empty) (*TaxonomyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaxonomies not implemented")
}
func (UnimplementedVibeCMSHostServer) UpdateTaxonomy(context.Context, *UpdateTaxonomyRequest) (*TaxonomyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTaxonomy not implemented")
}
func (UnimplementedVibeCMSHostServer) DeleteTaxonomy(context.Context, *DeleteTaxonomyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTaxonomy not implemented")
}
func (UnimplementedVibeCMSHostServer) GetSetting(context.Context, *GetSettingRequest) (*SettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSetting not implemented")
}
func (UnimplementedVibeCMSHostServer) SetSetting(context.Context, *SetSettingRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSetting not implemented")
}
func (UnimplementedVibeCMSHostServer) GetSettings(context.Context, *GetSettingsRequest) (*SettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedVibeCMSHostServer) EmitEvent(context.Context, *EmitEventRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitEvent not implemented")
}
func (UnimplementedVibeCMSHostServer) SendEmail(context.Context, *SendEmailRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedVibeCMSHostServer) GetMenu(context.Context, *GetMenuRequest) (*MenuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenu not implemented")
}
func (UnimplementedVibeCMSHostServer) GetMenus(context.Context, *Empty) (*MenuListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenus not implemented")
}
func (UnimplementedVibeCMSHostServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedVibeCMSHostServer) QueryUsers(context.Context, *QueryUsersRequest) (*UserListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryUsers not implemented")
}
func (UnimplementedVibeCMSHostServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedVibeCMSHostServer) Log(context.Context, *LogRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedVibeCMSHostServer) DataGet(context.Context, *DataGetRequest) (*DataRowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataGet not implemented")
}
func (UnimplementedVibeCMSHostServer) DataQuery(context.Context, *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataQuery not implemented")
}
func (UnimplementedVibeCMSHostServer) DataCreate(context.Context, *DataCreateRequest) (*DataRowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataCreate not implemented")
}
func (UnimplementedVibeCMSHostServer) DataUpdate(context.Context, *DataUpdateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DataUpdate not implemented")
}
func (UnimplementedVibeCMSHostServer) DataDelete(context.Context, *DataDeleteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DataDelete not implemented")
}
func (UnimplementedVibeCMSHostServer) DataExec(context.Context, *DataExecRequest) (*DataExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DataExec not implemented")
}
func (UnimplementedVibeCMSHostServer) StoreFile(context.Context, *StoreFileRequest) (*StoreFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreFile not implemented")
}
func (UnimplementedVibeCMSHostServer) DeleteFile(context.Context, *DeleteFileRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedVibeCMSHostServer) RegisterNodeType(context.Context, *NodeTypeInputMessage) (*NodeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNodeType not implemented")
}
func (UnimplementedVibeCMSHostServer) GetNodeType(context.Context, *GetNodeTypeRequest) (*NodeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeType not implemented")
}
func (UnimplementedVibeCMSHostServer) ListNodeTypes(context.Context, *Empty) (*NodeTypeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodeTypes not implemented")
}
func (UnimplementedVibeCMSHostServer) UpdateNodeType(context.Context, *UpdateNodeTypeRequest) (*NodeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNodeType not implemented")
}
func (UnimplementedVibeCMSHostServer) DeleteNodeType(context.Context, *DeleteNodeTypeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNodeType not implemented")
}
func (UnimplementedVibeCMSHostServer) mustEmbedUnimplementedVibeCMSHostServer() {}
func (UnimplementedVibeCMSHostServer) testEmbeddedByValue()                     {}

// UnsafeVibeCMSHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VibeCMSHostServer will
// result in compilation errors.
type UnsafeVibeCMSHostServer interface {
	mustEmbedUnimplementedVibeCMSHostServer()
}

func RegisterVibeCMSHostServer(s grpc.ServiceRegistrar, srv VibeCMSHostServer) {
	// If the following call panics, it indicates UnimplementedVibeCMSHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VibeCMSHost_ServiceDesc, srv)
}

func _VibeCMSHost_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_QueryNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).QueryNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_QueryNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).QueryNodes(ctx, req.(*QueryNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_ListTaxonomyTerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaxonomyTermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).ListTaxonomyTerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_ListTaxonomyTerms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).ListTaxonomyTerms(ctx, req.(*ListTaxonomyTermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_ListTerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).ListTerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_ListTerms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).ListTerms(ctx, req.(*ListTermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_GetTerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).GetTerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_GetTerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).GetTerm(ctx, req.(*GetTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_CreateTerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).CreateTerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_CreateTerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).CreateTerm(ctx, req.(*CreateTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_UpdateTerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).UpdateTerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_UpdateTerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).UpdateTerm(ctx, req.(*UpdateTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DeleteTerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DeleteTerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DeleteTerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DeleteTerm(ctx, req.(*DeleteTermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_RegisterTaxonomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaxonomyInputMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).RegisterTaxonomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_RegisterTaxonomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).RegisterTaxonomy(ctx, req.(*TaxonomyInputMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_GetTaxonomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaxonomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).GetTaxonomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_GetTaxonomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).GetTaxonomy(ctx, req.(*GetTaxonomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_ListTaxonomies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).ListTaxonomies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_ListTaxonomies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).ListTaxonomies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_UpdateTaxonomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaxonomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).UpdateTaxonomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_UpdateTaxonomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).UpdateTaxonomy(ctx, req.(*UpdateTaxonomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DeleteTaxonomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaxonomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DeleteTaxonomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DeleteTaxonomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DeleteTaxonomy(ctx, req.(*DeleteTaxonomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_GetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).GetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_GetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).GetSetting(ctx, req.(*GetSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_SetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).SetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_SetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).SetSetting(ctx, req.(*SetSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_EmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).EmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_EmitEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).EmitEvent(ctx, req.(*EmitEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_GetMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).GetMenu(ctx, req.(*GetMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_GetMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).GetMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_GetMenus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).GetMenus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_QueryUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).QueryUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_QueryUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).QueryUsers(ctx, req.(*QueryUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DataGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DataGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DataGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DataGet(ctx, req.(*DataGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DataQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DataQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DataQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DataQuery(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DataCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DataCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DataCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DataCreate(ctx, req.(*DataCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DataUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DataUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DataUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DataUpdate(ctx, req.(*DataUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DataDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DataDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DataDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DataDelete(ctx, req.(*DataDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DataExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DataExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DataExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DataExec(ctx, req.(*DataExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_StoreFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).StoreFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_StoreFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).StoreFile(ctx, req.(*StoreFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_RegisterNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeTypeInputMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).RegisterNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_RegisterNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).RegisterNodeType(ctx, req.(*NodeTypeInputMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_GetNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).GetNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_GetNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).GetNodeType(ctx, req.(*GetNodeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_ListNodeTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).ListNodeTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_ListNodeTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).ListNodeTypes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_UpdateNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).UpdateNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_UpdateNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).UpdateNodeType(ctx, req.(*UpdateNodeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VibeCMSHost_DeleteNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VibeCMSHostServer).DeleteNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VibeCMSHost_DeleteNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VibeCMSHostServer).DeleteNodeType(ctx, req.(*DeleteNodeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VibeCMSHost_ServiceDesc is the grpc.ServiceDesc for VibeCMSHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VibeCMSHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vibecms.coreapi.VibeCMSHost",
	HandlerType: (*VibeCMSHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNode",
			Handler:    _VibeCMSHost_GetNode_Handler,
		},
		{
			MethodName: "QueryNodes",
			Handler:    _VibeCMSHost_QueryNodes_Handler,
		},
		{
			MethodName: "ListTaxonomyTerms",
			Handler:    _VibeCMSHost_ListTaxonomyTerms_Handler,
		},
		{
			MethodName: "CreateNode",
			Handler:    _VibeCMSHost_CreateNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _VibeCMSHost_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _VibeCMSHost_DeleteNode_Handler,
		},
		{
			MethodName: "ListTerms",
			Handler:    _VibeCMSHost_ListTerms_Handler,
		},
		{
			MethodName: "GetTerm",
			Handler:    _VibeCMSHost_GetTerm_Handler,
		},
		{
			MethodName: "CreateTerm",
			Handler:    _VibeCMSHost_CreateTerm_Handler,
		},
		{
			MethodName: "UpdateTerm",
			Handler:    _VibeCMSHost_UpdateTerm_Handler,
		},
		{
			MethodName: "DeleteTerm",
			Handler:    _VibeCMSHost_DeleteTerm_Handler,
		},
		{
			MethodName: "RegisterTaxonomy",
			Handler:    _VibeCMSHost_RegisterTaxonomy_Handler,
		},
		{
			MethodName: "GetTaxonomy",
			Handler:    _VibeCMSHost_GetTaxonomy_Handler,
		},
		{
			MethodName: "ListTaxonomies",
			Handler:    _VibeCMSHost_ListTaxonomies_Handler,
		},
		{
			MethodName: "UpdateTaxonomy",
			Handler:    _VibeCMSHost_UpdateTaxonomy_Handler,
		},
		{
			MethodName: "DeleteTaxonomy",
			Handler:    _VibeCMSHost_DeleteTaxonomy_Handler,
		},
		{
			MethodName: "GetSetting",
			Handler:    _VibeCMSHost_GetSetting_Handler,
		},
		{
			MethodName: "SetSetting",
			Handler:    _VibeCMSHost_SetSetting_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _VibeCMSHost_GetSettings_Handler,
		},
		{
			MethodName: "EmitEvent",
			Handler:    _VibeCMSHost_EmitEvent_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _VibeCMSHost_SendEmail_Handler,
		},
		{
			MethodName: "GetMenu",
			Handler:    _VibeCMSHost_GetMenu_Handler,
		},
		{
			MethodName: "GetMenus",
			Handler:    _VibeCMSHost_GetMenus_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _VibeCMSHost_GetUser_Handler,
		},
		{
			MethodName: "QueryUsers",
			Handler:    _VibeCMSHost_QueryUsers_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _VibeCMSHost_Fetch_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _VibeCMSHost_Log_Handler,
		},
		{
			MethodName: "DataGet",
			Handler:    _VibeCMSHost_DataGet_Handler,
		},
		{
			MethodName: "DataQuery",
			Handler:    _VibeCMSHost_DataQuery_Handler,
		},
		{
			MethodName: "DataCreate",
			Handler:    _VibeCMSHost_DataCreate_Handler,
		},
		{
			MethodName: "DataUpdate",
			Handler:    _VibeCMSHost_DataUpdate_Handler,
		},
		{
			MethodName: "DataDelete",
			Handler:    _VibeCMSHost_DataDelete_Handler,
		},
		{
			MethodName: "DataExec",
			Handler:    _VibeCMSHost_DataExec_Handler,
		},
		{
			MethodName: "StoreFile",
			Handler:    _VibeCMSHost_StoreFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _VibeCMSHost_DeleteFile_Handler,
		},
		{
			MethodName: "RegisterNodeType",
			Handler:    _VibeCMSHost_RegisterNodeType_Handler,
		},
		{
			MethodName: "GetNodeType",
			Handler:    _VibeCMSHost_GetNodeType_Handler,
		},
		{
			MethodName: "ListNodeTypes",
			Handler:    _VibeCMSHost_ListNodeTypes_Handler,
		},
		{
			MethodName: "UpdateNodeType",
			Handler:    _VibeCMSHost_UpdateNodeType_Handler,
		},
		{
			MethodName: "DeleteNodeType",
			Handler:    _VibeCMSHost_DeleteNodeType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vibecms_coreapi.proto",
}
