package main

import (
	"context"
	"fmt"
	"log"
	"strings"

	goplugin "github.com/hashicorp/go-plugin"
	"google.golang.org/grpc"

	"squilla/internal/coreapi"
	vibeplugin "squilla/pkg/plugin"
	coreapipb "squilla/pkg/plugin/coreapipb"
	pb "squilla/pkg/plugin/proto"
)

// SEOPlugin owns /robots.txt generation and the SEO/robots admin
// settings schemas. The schemas are declared in extension.json and
// registered via the kernel's settings bridge automatically; this
// plugin only needs to implement the public route.
//
// The robots.txt logic was historically in internal/cms/robots_handler.go.
// Per the kernel/extensions hard rule (CLAUDE.md), SEO is a feature, not
// kernel infrastructure — disabling this extension cleanly removes
// /robots.txt without leaving dead code in the kernel.
type SEOPlugin struct {
	host *coreapi.GRPCHostClient
}

func (p *SEOPlugin) GetSubscriptions() ([]*pb.Subscription, error) {
	// "render.head" is the kernel's hook for injecting <head> content
	// on every public render. The kernel passes the full template-facing
	// node payload, settings, and translations — extensions extract
	// whatever they care about. This extension renders SEO/OG/Twitter
	// tags from the per-node `seo` JSONB and site settings; an analytics
	// or verification extension subscribing to the same event would add
	// its own tags alongside.
	return []*pb.Subscription{
		{EventName: "render.head", Priority: 50},
	}, nil
}

func (p *SEOPlugin) HandleEvent(action string, payload []byte) (*pb.EventResponse, error) {
	switch action {
	case "render.head":
		return p.handleRenderHead(payload)
	}
	return &pb.EventResponse{Handled: false}, nil
}

func (p *SEOPlugin) Shutdown() error { return nil }

func (p *SEOPlugin) Initialize(hostConn *grpc.ClientConn) error {
	p.host = coreapi.NewGRPCHostClient(coreapipb.NewSquillaHostClient(hostConn))
	return nil
}

func (p *SEOPlugin) HandleHTTPRequest(req *pb.PluginHTTPRequest) (*pb.PluginHTTPResponse, error) {
	method := strings.ToUpper(req.GetMethod())
	path := req.GetPath()

	if method == "GET" && (path == "/robots.txt" || strings.HasSuffix(path, "/robots.txt")) {
		return p.serveRobots(context.Background(), req)
	}

	return &pb.PluginHTTPResponse{
		StatusCode: 404,
		Headers:    map[string]string{"Content-Type": "text/plain; charset=utf-8"},
		Body:       []byte("not found"),
	}, nil
}

// aiTrainingBots are crawlers that scrape primarily to feed model
// training corpora. Blocking these keeps your content out of the next
// foundation model.
var aiTrainingBots = []string{
	"GPTBot",
	"ClaudeBot",
	"anthropic-ai",
	"Google-Extended",
	"Applebot-Extended",
	"CCBot",
	"Meta-ExternalAgent",
	"FacebookBot",
	"Bytespider",
	"Amazonbot",
	"Diffbot",
	"ImagesiftBot",
	"Omgilibot",
	"PetalBot",
	"AI2Bot",
	"DataForSeoBot",
	"Timpibot",
	"cohere-ai",
	"cohere-training-data-crawler",
	"Kangaroo Bot",
	"Scrapy",
	"Velen Crawler",
	"VelenPublicWebCrawler",
	"Webzio-Extended",
	"YouBot",
}

// aiSearchBots are crawlers that fetch live for an answer-engine when a
// user asks a question. Some operators want training blocked but search
// allowed (better citations) — hence the split toggle.
var aiSearchBots = []string{
	"ChatGPT-User",
	"OAI-SearchBot",
	"PerplexityBot",
	"Perplexity-User",
	"AndiBot",
	"phindbot",
	"DuckAssistBot",
	"MistralAI-User",
	"Bingbot",
	"GoogleOther",
}

func (p *SEOPlugin) serveRobots(ctx context.Context, req *pb.PluginHTTPRequest) (*pb.PluginHTTPResponse, error) {
	settings, err := p.host.GetSettings(ctx, "")
	if err != nil {
		log.Printf("[seo-extension] load settings: %v", err)
		settings = map[string]string{}
	}

	headers := map[string]string{
		"Content-Type":  "text/plain; charset=utf-8",
		"Cache-Control": "public, max-age=300",
	}

	// Master kill-switch: seo_robots_index=false means "stage / private —
	// keep everyone out". Don't second-guess by emitting partial rules.
	if !truthy(settings["seo_robots_index"], true) {
		var b strings.Builder
		b.WriteString("# Indexing disabled in Squilla → Site Settings → SEO.\n")
		b.WriteString("User-agent: *\n")
		b.WriteString("Disallow: /\n")
		return &pb.PluginHTTPResponse{StatusCode: 200, Headers: headers, Body: []byte(b.String())}, nil
	}

	var b strings.Builder
	b.WriteString("# Generated by Squilla. Edit at /admin/settings/seo and the Robots schema.\n\n")

	// Default policy block — every UA, plus operator-supplied
	// disallow paths.
	b.WriteString("User-agent: *\n")
	b.WriteString("Allow: /\n")
	// Sensible defaults so operators don't have to think about admin
	// surface area. /admin and /auth are core paths.
	b.WriteString("Disallow: /admin\n")
	b.WriteString("Disallow: /admin/\n")
	b.WriteString("Disallow: /auth/\n")
	b.WriteString("Disallow: /api/\n")
	for _, p := range splitLines(settings["robots_disallow_paths"]) {
		fmt.Fprintf(&b, "Disallow: %s\n", p)
	}
	b.WriteString("\n")

	// AI training opt-out.
	if !truthy(settings["robots_allow_ai_training"], true) {
		b.WriteString("# AI training crawlers — blocked via setting robots_allow_ai_training=false.\n")
		for _, ua := range aiTrainingBots {
			fmt.Fprintf(&b, "User-agent: %s\n", ua)
		}
		b.WriteString("Disallow: /\n\n")
	}

	// AI search / answer-engine opt-out.
	if !truthy(settings["robots_allow_ai_search"], true) {
		b.WriteString("# AI search / answer-engine crawlers — blocked via setting robots_allow_ai_search=false.\n")
		for _, ua := range aiSearchBots {
			fmt.Fprintf(&b, "User-agent: %s\n", ua)
		}
		b.WriteString("Disallow: /\n\n")
	}

	// Custom rules — appended verbatim, no parsing.
	if custom := strings.TrimSpace(settings["robots_custom"]); custom != "" {
		b.WriteString("# Custom rules:\n")
		b.WriteString(custom)
		if !strings.HasSuffix(custom, "\n") {
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// Sitemap line. Order: explicit override > derived from site_url >
	// request-host fallback (using the Host header from the proxied request).
	for _, sm := range sitemapURLs(settings, req) {
		fmt.Fprintf(&b, "Sitemap: %s\n", sm)
	}

	return &pb.PluginHTTPResponse{StatusCode: 200, Headers: headers, Body: []byte(b.String())}, nil
}

// sitemapURLs returns one or more absolute sitemap URLs to advertise.
// Order: explicit override > derived from site_url > request-host
// fallback. The fallback uses the Host header from the proxied request.
func sitemapURLs(s map[string]string, req *pb.PluginHTTPRequest) []string {
	if override := strings.TrimSpace(s["robots_sitemap_url"]); override != "" {
		return []string{override}
	}
	if base := strings.TrimSpace(s["site_url"]); base != "" {
		return []string{strings.TrimRight(base, "/") + "/sitemap.xml"}
	}
	scheme := "http"
	if proto := req.GetHeaders()["X-Forwarded-Proto"]; strings.EqualFold(proto, "https") {
		scheme = "https"
	}
	host := req.GetHeaders()["Host"]
	if host == "" {
		host = req.GetHeaders()["X-Forwarded-Host"]
	}
	if host == "" {
		return nil
	}
	return []string{fmt.Sprintf("%s://%s/sitemap.xml", scheme, host)}
}

// truthy interprets a setting value as boolean, falling back to dflt
// when unset. Accepts "true"/"1"/"on"/"yes" in any case.
func truthy(v string, dflt bool) bool {
	v = strings.TrimSpace(strings.ToLower(v))
	if v == "" {
		return dflt
	}
	switch v {
	case "true", "1", "on", "yes":
		return true
	default:
		return false
	}
}

// splitLines splits operator-supplied multiline text into trimmed,
// non-empty entries. Comment lines (#) survive.
func splitLines(s string) []string {
	if s == "" {
		return nil
	}
	parts := strings.Split(s, "\n")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		out = append(out, p)
	}
	return out
}

func main() {
	goplugin.Serve(&goplugin.ServeConfig{
		HandshakeConfig: vibeplugin.Handshake,
		VersionedPlugins: map[int]goplugin.PluginSet{
			2: {"extension": &vibeplugin.ExtensionGRPCPlugin{Impl: &SEOPlugin{}}},
		},
		GRPCServer: vibeplugin.NewGRPCServer,
	})
}
